// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apollo_msgs/proto/localization/localization_config.proto

#ifndef PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto
#define PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto 

namespace protobuf_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto
namespace apollo {
namespace localization {
class LocalizationConfig;
class LocalizationConfigDefaultTypeInternal;
extern LocalizationConfigDefaultTypeInternal _LocalizationConfig_default_instance_;
}  // namespace localization
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::localization::LocalizationConfig* Arena::CreateMaybeMessage<::apollo::localization::LocalizationConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace localization {

enum LocalizationConfig_LocalizationType {
  LocalizationConfig_LocalizationType_RTK = 0,
  LocalizationConfig_LocalizationType_CAMERA = 1,
  LocalizationConfig_LocalizationType_LocalizationConfig_LocalizationType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  LocalizationConfig_LocalizationType_LocalizationConfig_LocalizationType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool LocalizationConfig_LocalizationType_IsValid(int value);
const LocalizationConfig_LocalizationType LocalizationConfig_LocalizationType_LocalizationType_MIN = LocalizationConfig_LocalizationType_RTK;
const LocalizationConfig_LocalizationType LocalizationConfig_LocalizationType_LocalizationType_MAX = LocalizationConfig_LocalizationType_CAMERA;
const int LocalizationConfig_LocalizationType_LocalizationType_ARRAYSIZE = LocalizationConfig_LocalizationType_LocalizationType_MAX + 1;

const ::google::protobuf::EnumDescriptor* LocalizationConfig_LocalizationType_descriptor();
inline const ::std::string& LocalizationConfig_LocalizationType_Name(LocalizationConfig_LocalizationType value) {
  return ::google::protobuf::internal::NameOfEnum(
    LocalizationConfig_LocalizationType_descriptor(), value);
}
inline bool LocalizationConfig_LocalizationType_Parse(
    const ::std::string& name, LocalizationConfig_LocalizationType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<LocalizationConfig_LocalizationType>(
    LocalizationConfig_LocalizationType_descriptor(), name, value);
}
// ===================================================================

class LocalizationConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.localization.LocalizationConfig) */ {
 public:
  LocalizationConfig();
  virtual ~LocalizationConfig();

  LocalizationConfig(const LocalizationConfig& from);

  inline LocalizationConfig& operator=(const LocalizationConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LocalizationConfig(LocalizationConfig&& from) noexcept
    : LocalizationConfig() {
    *this = ::std::move(from);
  }

  inline LocalizationConfig& operator=(LocalizationConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LocalizationConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LocalizationConfig* internal_default_instance() {
    return reinterpret_cast<const LocalizationConfig*>(
               &_LocalizationConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(LocalizationConfig* other);
  friend void swap(LocalizationConfig& a, LocalizationConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LocalizationConfig* New() const final {
    return CreateMaybeMessage<LocalizationConfig>(NULL);
  }

  LocalizationConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LocalizationConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LocalizationConfig& from);
  void MergeFrom(const LocalizationConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LocalizationConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef LocalizationConfig_LocalizationType LocalizationType;
  static const LocalizationType RTK =
    LocalizationConfig_LocalizationType_RTK;
  static const LocalizationType CAMERA =
    LocalizationConfig_LocalizationType_CAMERA;
  static inline bool LocalizationType_IsValid(int value) {
    return LocalizationConfig_LocalizationType_IsValid(value);
  }
  static const LocalizationType LocalizationType_MIN =
    LocalizationConfig_LocalizationType_LocalizationType_MIN;
  static const LocalizationType LocalizationType_MAX =
    LocalizationConfig_LocalizationType_LocalizationType_MAX;
  static const int LocalizationType_ARRAYSIZE =
    LocalizationConfig_LocalizationType_LocalizationType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  LocalizationType_descriptor() {
    return LocalizationConfig_LocalizationType_descriptor();
  }
  static inline const ::std::string& LocalizationType_Name(LocalizationType value) {
    return LocalizationConfig_LocalizationType_Name(value);
  }
  static inline bool LocalizationType_Parse(const ::std::string& name,
      LocalizationType* value) {
    return LocalizationConfig_LocalizationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .apollo.localization.LocalizationConfig.LocalizationType localization_type = 1;
  void clear_localization_type();
  static const int kLocalizationTypeFieldNumber = 1;
  ::apollo::localization::LocalizationConfig_LocalizationType localization_type() const;
  void set_localization_type(::apollo::localization::LocalizationConfig_LocalizationType value);

  // @@protoc_insertion_point(class_scope:apollo.localization.LocalizationConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int localization_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LocalizationConfig

// .apollo.localization.LocalizationConfig.LocalizationType localization_type = 1;
inline void LocalizationConfig::clear_localization_type() {
  localization_type_ = 0;
}
inline ::apollo::localization::LocalizationConfig_LocalizationType LocalizationConfig::localization_type() const {
  // @@protoc_insertion_point(field_get:apollo.localization.LocalizationConfig.localization_type)
  return static_cast< ::apollo::localization::LocalizationConfig_LocalizationType >(localization_type_);
}
inline void LocalizationConfig::set_localization_type(::apollo::localization::LocalizationConfig_LocalizationType value) {
  
  localization_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.localization.LocalizationConfig.localization_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace localization
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::localization::LocalizationConfig_LocalizationType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::localization::LocalizationConfig_LocalizationType>() {
  return ::apollo::localization::LocalizationConfig_LocalizationType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2flocalization_2flocalization_5fconfig_2eproto
