// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apollo_msgs/proto/planning/planning_internal.proto

#ifndef PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto
#define PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "apollo_msgs/proto/common/header.pb.h"
#include "apollo_msgs/proto/decision/decision.pb.h"
#include "apollo_msgs/proto/localization/localization.pb.h"
#include "apollo_msgs/proto/localization/pose.pb.h"
#include "apollo_msgs/proto/perception/perception_obstacle.pb.h"
#include "apollo_msgs/proto/prediction/prediction_obstacle.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto 

namespace protobuf_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto
namespace apollo {
namespace planning_internal {
class Debug;
class DebugDefaultTypeInternal;
extern DebugDefaultTypeInternal _Debug_default_instance_;
class Debug_DebugMessage;
class Debug_DebugMessageDefaultTypeInternal;
extern Debug_DebugMessageDefaultTypeInternal _Debug_DebugMessage_default_instance_;
class PlanningData;
class PlanningDataDefaultTypeInternal;
extern PlanningDataDefaultTypeInternal _PlanningData_default_instance_;
class PlanningObstacle;
class PlanningObstacleDefaultTypeInternal;
extern PlanningObstacleDefaultTypeInternal _PlanningObstacle_default_instance_;
}  // namespace planning_internal
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::planning_internal::Debug* Arena::CreateMaybeMessage<::apollo::planning_internal::Debug>(Arena*);
template<> ::apollo::planning_internal::Debug_DebugMessage* Arena::CreateMaybeMessage<::apollo::planning_internal::Debug_DebugMessage>(Arena*);
template<> ::apollo::planning_internal::PlanningData* Arena::CreateMaybeMessage<::apollo::planning_internal::PlanningData>(Arena*);
template<> ::apollo::planning_internal::PlanningObstacle* Arena::CreateMaybeMessage<::apollo::planning_internal::PlanningObstacle>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace planning_internal {

enum Debug_ErrorCode {
  Debug_ErrorCode_OK = 0,
  Debug_ErrorCode_ERR_NOT_READY = 1,
  Debug_ErrorCode_ERR_ESTOP = 2,
  Debug_ErrorCode_ERR_PATH_OPTIMIZER = 3,
  Debug_ErrorCode_ERR_SPEED_OPTIMIZER = 4,
  Debug_ErrorCode_ERR_ST_GRAPH = 5,
  Debug_ErrorCode_ERR_SANITY_CHECK = 6,
  Debug_ErrorCode_Debug_ErrorCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Debug_ErrorCode_Debug_ErrorCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Debug_ErrorCode_IsValid(int value);
const Debug_ErrorCode Debug_ErrorCode_ErrorCode_MIN = Debug_ErrorCode_OK;
const Debug_ErrorCode Debug_ErrorCode_ErrorCode_MAX = Debug_ErrorCode_ERR_SANITY_CHECK;
const int Debug_ErrorCode_ErrorCode_ARRAYSIZE = Debug_ErrorCode_ErrorCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* Debug_ErrorCode_descriptor();
inline const ::std::string& Debug_ErrorCode_Name(Debug_ErrorCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    Debug_ErrorCode_descriptor(), value);
}
inline bool Debug_ErrorCode_Parse(
    const ::std::string& name, Debug_ErrorCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Debug_ErrorCode>(
    Debug_ErrorCode_descriptor(), name, value);
}
// ===================================================================

class PlanningObstacle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning_internal.PlanningObstacle) */ {
 public:
  PlanningObstacle();
  virtual ~PlanningObstacle();

  PlanningObstacle(const PlanningObstacle& from);

  inline PlanningObstacle& operator=(const PlanningObstacle& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlanningObstacle(PlanningObstacle&& from) noexcept
    : PlanningObstacle() {
    *this = ::std::move(from);
  }

  inline PlanningObstacle& operator=(PlanningObstacle&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlanningObstacle& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlanningObstacle* internal_default_instance() {
    return reinterpret_cast<const PlanningObstacle*>(
               &_PlanningObstacle_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(PlanningObstacle* other);
  friend void swap(PlanningObstacle& a, PlanningObstacle& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlanningObstacle* New() const final {
    return CreateMaybeMessage<PlanningObstacle>(NULL);
  }

  PlanningObstacle* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PlanningObstacle>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PlanningObstacle& from);
  void MergeFrom(const PlanningObstacle& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlanningObstacle* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.perception.Point polygon_point = 10;
  int polygon_point_size() const;
  void clear_polygon_point();
  static const int kPolygonPointFieldNumber = 10;
  ::apollo::perception::Point* mutable_polygon_point(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >*
      mutable_polygon_point();
  const ::apollo::perception::Point& polygon_point(int index) const;
  ::apollo::perception::Point* add_polygon_point();
  const ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >&
      polygon_point() const;

  // repeated .apollo.prediction.Trajectory prediction_trajectory = 15;
  int prediction_trajectory_size() const;
  void clear_prediction_trajectory();
  static const int kPredictionTrajectoryFieldNumber = 15;
  ::apollo::prediction::Trajectory* mutable_prediction_trajectory(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::prediction::Trajectory >*
      mutable_prediction_trajectory();
  const ::apollo::prediction::Trajectory& prediction_trajectory(int index) const;
  ::apollo::prediction::Trajectory* add_prediction_trajectory();
  const ::google::protobuf::RepeatedPtrField< ::apollo::prediction::Trajectory >&
      prediction_trajectory() const;

  // repeated .apollo.decision.ObjectDecisionType planning_object_decision = 18;
  int planning_object_decision_size() const;
  void clear_planning_object_decision();
  static const int kPlanningObjectDecisionFieldNumber = 18;
  ::apollo::decision::ObjectDecisionType* mutable_planning_object_decision(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::decision::ObjectDecisionType >*
      mutable_planning_object_decision();
  const ::apollo::decision::ObjectDecisionType& planning_object_decision(int index) const;
  ::apollo::decision::ObjectDecisionType* add_planning_object_decision();
  const ::google::protobuf::RepeatedPtrField< ::apollo::decision::ObjectDecisionType >&
      planning_object_decision() const;

  // string decision_id = 2;
  void clear_decision_id();
  static const int kDecisionIdFieldNumber = 2;
  const ::std::string& decision_id() const;
  void set_decision_id(const ::std::string& value);
  #if LANG_CXX11
  void set_decision_id(::std::string&& value);
  #endif
  void set_decision_id(const char* value);
  void set_decision_id(const char* value, size_t size);
  ::std::string* mutable_decision_id();
  ::std::string* release_decision_id();
  void set_allocated_decision_id(::std::string* decision_id);

  // .apollo.perception.Point position = 3;
  bool has_position() const;
  void clear_position();
  static const int kPositionFieldNumber = 3;
  private:
  const ::apollo::perception::Point& _internal_position() const;
  public:
  const ::apollo::perception::Point& position() const;
  ::apollo::perception::Point* release_position();
  ::apollo::perception::Point* mutable_position();
  void set_allocated_position(::apollo::perception::Point* position);

  // .apollo.perception.Point velocity = 5;
  bool has_velocity() const;
  void clear_velocity();
  static const int kVelocityFieldNumber = 5;
  private:
  const ::apollo::perception::Point& _internal_velocity() const;
  public:
  const ::apollo::perception::Point& velocity() const;
  ::apollo::perception::Point* release_velocity();
  ::apollo::perception::Point* mutable_velocity();
  void set_allocated_velocity(::apollo::perception::Point* velocity);

  // .apollo.decision.ObjectDecisionType object_decision = 17;
  bool has_object_decision() const;
  void clear_object_decision();
  static const int kObjectDecisionFieldNumber = 17;
  private:
  const ::apollo::decision::ObjectDecisionType& _internal_object_decision() const;
  public:
  const ::apollo::decision::ObjectDecisionType& object_decision() const;
  ::apollo::decision::ObjectDecisionType* release_object_decision();
  ::apollo::decision::ObjectDecisionType* mutable_object_decision();
  void set_allocated_object_decision(::apollo::decision::ObjectDecisionType* object_decision);

  // double theta = 4;
  void clear_theta();
  static const int kThetaFieldNumber = 4;
  double theta() const;
  void set_theta(double value);

  // double speed = 6;
  void clear_speed();
  static const int kSpeedFieldNumber = 6;
  double speed() const;
  void set_speed(double value);

  // double length = 7;
  void clear_length();
  static const int kLengthFieldNumber = 7;
  double length() const;
  void set_length(double value);

  // int32 perception_id = 1;
  void clear_perception_id();
  static const int kPerceptionIdFieldNumber = 1;
  ::google::protobuf::int32 perception_id() const;
  void set_perception_id(::google::protobuf::int32 value);

  // .apollo.perception.PerceptionObstacle.Type perception_object_type = 13;
  void clear_perception_object_type();
  static const int kPerceptionObjectTypeFieldNumber = 13;
  ::apollo::perception::PerceptionObstacle_Type perception_object_type() const;
  void set_perception_object_type(::apollo::perception::PerceptionObstacle_Type value);

  // double width = 8;
  void clear_width();
  static const int kWidthFieldNumber = 8;
  double width() const;
  void set_width(double value);

  // double height = 9;
  void clear_height();
  static const int kHeightFieldNumber = 9;
  double height() const;
  void set_height(double value);

  // double tracking_time = 11;
  void clear_tracking_time();
  static const int kTrackingTimeFieldNumber = 11;
  double tracking_time() const;
  void set_tracking_time(double value);

  // double perception_timestamp = 12;
  void clear_perception_timestamp();
  static const int kPerceptionTimestampFieldNumber = 12;
  double perception_timestamp() const;
  void set_perception_timestamp(double value);

  // double prediction_timestamp = 14;
  void clear_prediction_timestamp();
  static const int kPredictionTimestampFieldNumber = 14;
  double prediction_timestamp() const;
  void set_prediction_timestamp(double value);

  // .apollo.decision.ObjectDecision.ObjectType decision_object_type = 16;
  void clear_decision_object_type();
  static const int kDecisionObjectTypeFieldNumber = 16;
  ::apollo::decision::ObjectDecision_ObjectType decision_object_type() const;
  void set_decision_object_type(::apollo::decision::ObjectDecision_ObjectType value);

  // @@protoc_insertion_point(class_scope:apollo.planning_internal.PlanningObstacle)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point > polygon_point_;
  ::google::protobuf::RepeatedPtrField< ::apollo::prediction::Trajectory > prediction_trajectory_;
  ::google::protobuf::RepeatedPtrField< ::apollo::decision::ObjectDecisionType > planning_object_decision_;
  ::google::protobuf::internal::ArenaStringPtr decision_id_;
  ::apollo::perception::Point* position_;
  ::apollo::perception::Point* velocity_;
  ::apollo::decision::ObjectDecisionType* object_decision_;
  double theta_;
  double speed_;
  double length_;
  ::google::protobuf::int32 perception_id_;
  int perception_object_type_;
  double width_;
  double height_;
  double tracking_time_;
  double perception_timestamp_;
  double prediction_timestamp_;
  int decision_object_type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Debug_DebugMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning_internal.Debug.DebugMessage) */ {
 public:
  Debug_DebugMessage();
  virtual ~Debug_DebugMessage();

  Debug_DebugMessage(const Debug_DebugMessage& from);

  inline Debug_DebugMessage& operator=(const Debug_DebugMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Debug_DebugMessage(Debug_DebugMessage&& from) noexcept
    : Debug_DebugMessage() {
    *this = ::std::move(from);
  }

  inline Debug_DebugMessage& operator=(Debug_DebugMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Debug_DebugMessage& default_instance();

  enum DebugStringCase {
    kTrace = 3,
    kInfo = 4,
    kWarn = 5,
    kError = 6,
    kFatal = 7,
    DEBUG_STRING_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Debug_DebugMessage* internal_default_instance() {
    return reinterpret_cast<const Debug_DebugMessage*>(
               &_Debug_DebugMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Debug_DebugMessage* other);
  friend void swap(Debug_DebugMessage& a, Debug_DebugMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Debug_DebugMessage* New() const final {
    return CreateMaybeMessage<Debug_DebugMessage>(NULL);
  }

  Debug_DebugMessage* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Debug_DebugMessage>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Debug_DebugMessage& from);
  void MergeFrom(const Debug_DebugMessage& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Debug_DebugMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .apollo.planning_internal.Debug.ErrorCode error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::apollo::planning_internal::Debug_ErrorCode error_code() const;
  void set_error_code(::apollo::planning_internal::Debug_ErrorCode value);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // string trace = 3;
  private:
  bool has_trace() const;
  public:
  void clear_trace();
  static const int kTraceFieldNumber = 3;
  const ::std::string& trace() const;
  void set_trace(const ::std::string& value);
  #if LANG_CXX11
  void set_trace(::std::string&& value);
  #endif
  void set_trace(const char* value);
  void set_trace(const char* value, size_t size);
  ::std::string* mutable_trace();
  ::std::string* release_trace();
  void set_allocated_trace(::std::string* trace);

  // string info = 4;
  private:
  bool has_info() const;
  public:
  void clear_info();
  static const int kInfoFieldNumber = 4;
  const ::std::string& info() const;
  void set_info(const ::std::string& value);
  #if LANG_CXX11
  void set_info(::std::string&& value);
  #endif
  void set_info(const char* value);
  void set_info(const char* value, size_t size);
  ::std::string* mutable_info();
  ::std::string* release_info();
  void set_allocated_info(::std::string* info);

  // string warn = 5;
  private:
  bool has_warn() const;
  public:
  void clear_warn();
  static const int kWarnFieldNumber = 5;
  const ::std::string& warn() const;
  void set_warn(const ::std::string& value);
  #if LANG_CXX11
  void set_warn(::std::string&& value);
  #endif
  void set_warn(const char* value);
  void set_warn(const char* value, size_t size);
  ::std::string* mutable_warn();
  ::std::string* release_warn();
  void set_allocated_warn(::std::string* warn);

  // string error = 6;
  private:
  bool has_error() const;
  public:
  void clear_error();
  static const int kErrorFieldNumber = 6;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // string fatal = 7;
  private:
  bool has_fatal() const;
  public:
  void clear_fatal();
  static const int kFatalFieldNumber = 7;
  const ::std::string& fatal() const;
  void set_fatal(const ::std::string& value);
  #if LANG_CXX11
  void set_fatal(::std::string&& value);
  #endif
  void set_fatal(const char* value);
  void set_fatal(const char* value, size_t size);
  ::std::string* mutable_fatal();
  ::std::string* release_fatal();
  void set_allocated_fatal(::std::string* fatal);

  void clear_debug_string();
  DebugStringCase debug_string_case() const;
  // @@protoc_insertion_point(class_scope:apollo.planning_internal.Debug.DebugMessage)
 private:
  void set_has_trace();
  void set_has_info();
  void set_has_warn();
  void set_has_error();
  void set_has_fatal();

  inline bool has_debug_string() const;
  inline void clear_has_debug_string();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int error_code_;
  ::google::protobuf::int32 id_;
  union DebugStringUnion {
    DebugStringUnion() {}
    ::google::protobuf::internal::ArenaStringPtr trace_;
    ::google::protobuf::internal::ArenaStringPtr info_;
    ::google::protobuf::internal::ArenaStringPtr warn_;
    ::google::protobuf::internal::ArenaStringPtr error_;
    ::google::protobuf::internal::ArenaStringPtr fatal_;
  } debug_string_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Debug : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning_internal.Debug) */ {
 public:
  Debug();
  virtual ~Debug();

  Debug(const Debug& from);

  inline Debug& operator=(const Debug& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Debug(Debug&& from) noexcept
    : Debug() {
    *this = ::std::move(from);
  }

  inline Debug& operator=(Debug&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Debug& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Debug* internal_default_instance() {
    return reinterpret_cast<const Debug*>(
               &_Debug_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Debug* other);
  friend void swap(Debug& a, Debug& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Debug* New() const final {
    return CreateMaybeMessage<Debug>(NULL);
  }

  Debug* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Debug>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Debug& from);
  void MergeFrom(const Debug& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Debug* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Debug_DebugMessage DebugMessage;

  typedef Debug_ErrorCode ErrorCode;
  static const ErrorCode OK =
    Debug_ErrorCode_OK;
  static const ErrorCode ERR_NOT_READY =
    Debug_ErrorCode_ERR_NOT_READY;
  static const ErrorCode ERR_ESTOP =
    Debug_ErrorCode_ERR_ESTOP;
  static const ErrorCode ERR_PATH_OPTIMIZER =
    Debug_ErrorCode_ERR_PATH_OPTIMIZER;
  static const ErrorCode ERR_SPEED_OPTIMIZER =
    Debug_ErrorCode_ERR_SPEED_OPTIMIZER;
  static const ErrorCode ERR_ST_GRAPH =
    Debug_ErrorCode_ERR_ST_GRAPH;
  static const ErrorCode ERR_SANITY_CHECK =
    Debug_ErrorCode_ERR_SANITY_CHECK;
  static inline bool ErrorCode_IsValid(int value) {
    return Debug_ErrorCode_IsValid(value);
  }
  static const ErrorCode ErrorCode_MIN =
    Debug_ErrorCode_ErrorCode_MIN;
  static const ErrorCode ErrorCode_MAX =
    Debug_ErrorCode_ErrorCode_MAX;
  static const int ErrorCode_ARRAYSIZE =
    Debug_ErrorCode_ErrorCode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ErrorCode_descriptor() {
    return Debug_ErrorCode_descriptor();
  }
  static inline const ::std::string& ErrorCode_Name(ErrorCode value) {
    return Debug_ErrorCode_Name(value);
  }
  static inline bool ErrorCode_Parse(const ::std::string& name,
      ErrorCode* value) {
    return Debug_ErrorCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .apollo.planning_internal.Debug.DebugMessage debug_message = 3;
  int debug_message_size() const;
  void clear_debug_message();
  static const int kDebugMessageFieldNumber = 3;
  ::apollo::planning_internal::Debug_DebugMessage* mutable_debug_message(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::Debug_DebugMessage >*
      mutable_debug_message();
  const ::apollo::planning_internal::Debug_DebugMessage& debug_message(int index) const;
  ::apollo::planning_internal::Debug_DebugMessage* add_debug_message();
  const ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::Debug_DebugMessage >&
      debug_message() const;

  // .apollo.planning_internal.PlanningData planning_data = 2;
  bool has_planning_data() const;
  void clear_planning_data();
  static const int kPlanningDataFieldNumber = 2;
  private:
  const ::apollo::planning_internal::PlanningData& _internal_planning_data() const;
  public:
  const ::apollo::planning_internal::PlanningData& planning_data() const;
  ::apollo::planning_internal::PlanningData* release_planning_data();
  ::apollo::planning_internal::PlanningData* mutable_planning_data();
  void set_allocated_planning_data(::apollo::planning_internal::PlanningData* planning_data);

  // .apollo.planning_internal.Debug.ErrorCode error_code = 1;
  void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  ::apollo::planning_internal::Debug_ErrorCode error_code() const;
  void set_error_code(::apollo::planning_internal::Debug_ErrorCode value);

  // @@protoc_insertion_point(class_scope:apollo.planning_internal.Debug)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::Debug_DebugMessage > debug_message_;
  ::apollo::planning_internal::PlanningData* planning_data_;
  int error_code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PlanningData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.planning_internal.PlanningData) */ {
 public:
  PlanningData();
  virtual ~PlanningData();

  PlanningData(const PlanningData& from);

  inline PlanningData& operator=(const PlanningData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlanningData(PlanningData&& from) noexcept
    : PlanningData() {
    *this = ::std::move(from);
  }

  inline PlanningData& operator=(PlanningData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlanningData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlanningData* internal_default_instance() {
    return reinterpret_cast<const PlanningData*>(
               &_PlanningData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(PlanningData* other);
  friend void swap(PlanningData& a, PlanningData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlanningData* New() const final {
    return CreateMaybeMessage<PlanningData>(NULL);
  }

  PlanningData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PlanningData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PlanningData& from);
  void MergeFrom(const PlanningData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlanningData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.planning_internal.PlanningObstacle planning_obstacle = 4;
  int planning_obstacle_size() const;
  void clear_planning_obstacle();
  static const int kPlanningObstacleFieldNumber = 4;
  ::apollo::planning_internal::PlanningObstacle* mutable_planning_obstacle(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::PlanningObstacle >*
      mutable_planning_obstacle();
  const ::apollo::planning_internal::PlanningObstacle& planning_obstacle(int index) const;
  ::apollo::planning_internal::PlanningObstacle* add_planning_obstacle();
  const ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::PlanningObstacle >&
      planning_obstacle() const;

  // .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::apollo::common::Header& _internal_header() const;
  public:
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);

  // .apollo.localization.Pose init_status = 2;
  bool has_init_status() const;
  void clear_init_status();
  static const int kInitStatusFieldNumber = 2;
  private:
  const ::apollo::localization::Pose& _internal_init_status() const;
  public:
  const ::apollo::localization::Pose& init_status() const;
  ::apollo::localization::Pose* release_init_status();
  ::apollo::localization::Pose* mutable_init_status();
  void set_allocated_init_status(::apollo::localization::Pose* init_status);

  // .apollo.decision.MainDecision main_decision = 3;
  bool has_main_decision() const;
  void clear_main_decision();
  static const int kMainDecisionFieldNumber = 3;
  private:
  const ::apollo::decision::MainDecision& _internal_main_decision() const;
  public:
  const ::apollo::decision::MainDecision& main_decision() const;
  ::apollo::decision::MainDecision* release_main_decision();
  ::apollo::decision::MainDecision* mutable_main_decision();
  void set_allocated_main_decision(::apollo::decision::MainDecision* main_decision);

  // .apollo.decision.LightSignal light_signal = 5;
  bool has_light_signal() const;
  void clear_light_signal();
  static const int kLightSignalFieldNumber = 5;
  private:
  const ::apollo::decision::LightSignal& _internal_light_signal() const;
  public:
  const ::apollo::decision::LightSignal& light_signal() const;
  ::apollo::decision::LightSignal* release_light_signal();
  ::apollo::decision::LightSignal* mutable_light_signal();
  void set_allocated_light_signal(::apollo::decision::LightSignal* light_signal);

  // @@protoc_insertion_point(class_scope:apollo.planning_internal.PlanningData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::PlanningObstacle > planning_obstacle_;
  ::apollo::common::Header* header_;
  ::apollo::localization::Pose* init_status_;
  ::apollo::decision::MainDecision* main_decision_;
  ::apollo::decision::LightSignal* light_signal_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlanningObstacle

// int32 perception_id = 1;
inline void PlanningObstacle::clear_perception_id() {
  perception_id_ = 0;
}
inline ::google::protobuf::int32 PlanningObstacle::perception_id() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.perception_id)
  return perception_id_;
}
inline void PlanningObstacle::set_perception_id(::google::protobuf::int32 value) {
  
  perception_id_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.perception_id)
}

// string decision_id = 2;
inline void PlanningObstacle::clear_decision_id() {
  decision_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlanningObstacle::decision_id() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.decision_id)
  return decision_id_.GetNoArena();
}
inline void PlanningObstacle::set_decision_id(const ::std::string& value) {
  
  decision_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.decision_id)
}
#if LANG_CXX11
inline void PlanningObstacle::set_decision_id(::std::string&& value) {
  
  decision_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.planning_internal.PlanningObstacle.decision_id)
}
#endif
inline void PlanningObstacle::set_decision_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  decision_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.planning_internal.PlanningObstacle.decision_id)
}
inline void PlanningObstacle::set_decision_id(const char* value, size_t size) {
  
  decision_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.planning_internal.PlanningObstacle.decision_id)
}
inline ::std::string* PlanningObstacle::mutable_decision_id() {
  
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningObstacle.decision_id)
  return decision_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlanningObstacle::release_decision_id() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningObstacle.decision_id)
  
  return decision_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlanningObstacle::set_allocated_decision_id(::std::string* decision_id) {
  if (decision_id != NULL) {
    
  } else {
    
  }
  decision_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), decision_id);
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningObstacle.decision_id)
}

// .apollo.perception.Point position = 3;
inline bool PlanningObstacle::has_position() const {
  return this != internal_default_instance() && position_ != NULL;
}
inline const ::apollo::perception::Point& PlanningObstacle::_internal_position() const {
  return *position_;
}
inline const ::apollo::perception::Point& PlanningObstacle::position() const {
  const ::apollo::perception::Point* p = position_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.position)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::perception::Point*>(
      &::apollo::perception::_Point_default_instance_);
}
inline ::apollo::perception::Point* PlanningObstacle::release_position() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningObstacle.position)
  
  ::apollo::perception::Point* temp = position_;
  position_ = NULL;
  return temp;
}
inline ::apollo::perception::Point* PlanningObstacle::mutable_position() {
  
  if (position_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::perception::Point>(GetArenaNoVirtual());
    position_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningObstacle.position)
  return position_;
}
inline void PlanningObstacle::set_allocated_position(::apollo::perception::Point* position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(position_);
  }
  if (position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    
  } else {
    
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningObstacle.position)
}

// double theta = 4;
inline void PlanningObstacle::clear_theta() {
  theta_ = 0;
}
inline double PlanningObstacle::theta() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.theta)
  return theta_;
}
inline void PlanningObstacle::set_theta(double value) {
  
  theta_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.theta)
}

// .apollo.perception.Point velocity = 5;
inline bool PlanningObstacle::has_velocity() const {
  return this != internal_default_instance() && velocity_ != NULL;
}
inline const ::apollo::perception::Point& PlanningObstacle::_internal_velocity() const {
  return *velocity_;
}
inline const ::apollo::perception::Point& PlanningObstacle::velocity() const {
  const ::apollo::perception::Point* p = velocity_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.velocity)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::perception::Point*>(
      &::apollo::perception::_Point_default_instance_);
}
inline ::apollo::perception::Point* PlanningObstacle::release_velocity() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningObstacle.velocity)
  
  ::apollo::perception::Point* temp = velocity_;
  velocity_ = NULL;
  return temp;
}
inline ::apollo::perception::Point* PlanningObstacle::mutable_velocity() {
  
  if (velocity_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::perception::Point>(GetArenaNoVirtual());
    velocity_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningObstacle.velocity)
  return velocity_;
}
inline void PlanningObstacle::set_allocated_velocity(::apollo::perception::Point* velocity) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(velocity_);
  }
  if (velocity) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      velocity = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, velocity, submessage_arena);
    }
    
  } else {
    
  }
  velocity_ = velocity;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningObstacle.velocity)
}

// double speed = 6;
inline void PlanningObstacle::clear_speed() {
  speed_ = 0;
}
inline double PlanningObstacle::speed() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.speed)
  return speed_;
}
inline void PlanningObstacle::set_speed(double value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.speed)
}

// double length = 7;
inline void PlanningObstacle::clear_length() {
  length_ = 0;
}
inline double PlanningObstacle::length() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.length)
  return length_;
}
inline void PlanningObstacle::set_length(double value) {
  
  length_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.length)
}

// double width = 8;
inline void PlanningObstacle::clear_width() {
  width_ = 0;
}
inline double PlanningObstacle::width() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.width)
  return width_;
}
inline void PlanningObstacle::set_width(double value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.width)
}

// double height = 9;
inline void PlanningObstacle::clear_height() {
  height_ = 0;
}
inline double PlanningObstacle::height() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.height)
  return height_;
}
inline void PlanningObstacle::set_height(double value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.height)
}

// repeated .apollo.perception.Point polygon_point = 10;
inline int PlanningObstacle::polygon_point_size() const {
  return polygon_point_.size();
}
inline ::apollo::perception::Point* PlanningObstacle::mutable_polygon_point(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningObstacle.polygon_point)
  return polygon_point_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >*
PlanningObstacle::mutable_polygon_point() {
  // @@protoc_insertion_point(field_mutable_list:apollo.planning_internal.PlanningObstacle.polygon_point)
  return &polygon_point_;
}
inline const ::apollo::perception::Point& PlanningObstacle::polygon_point(int index) const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.polygon_point)
  return polygon_point_.Get(index);
}
inline ::apollo::perception::Point* PlanningObstacle::add_polygon_point() {
  // @@protoc_insertion_point(field_add:apollo.planning_internal.PlanningObstacle.polygon_point)
  return polygon_point_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::perception::Point >&
PlanningObstacle::polygon_point() const {
  // @@protoc_insertion_point(field_list:apollo.planning_internal.PlanningObstacle.polygon_point)
  return polygon_point_;
}

// double tracking_time = 11;
inline void PlanningObstacle::clear_tracking_time() {
  tracking_time_ = 0;
}
inline double PlanningObstacle::tracking_time() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.tracking_time)
  return tracking_time_;
}
inline void PlanningObstacle::set_tracking_time(double value) {
  
  tracking_time_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.tracking_time)
}

// double perception_timestamp = 12;
inline void PlanningObstacle::clear_perception_timestamp() {
  perception_timestamp_ = 0;
}
inline double PlanningObstacle::perception_timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.perception_timestamp)
  return perception_timestamp_;
}
inline void PlanningObstacle::set_perception_timestamp(double value) {
  
  perception_timestamp_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.perception_timestamp)
}

// .apollo.perception.PerceptionObstacle.Type perception_object_type = 13;
inline void PlanningObstacle::clear_perception_object_type() {
  perception_object_type_ = 0;
}
inline ::apollo::perception::PerceptionObstacle_Type PlanningObstacle::perception_object_type() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.perception_object_type)
  return static_cast< ::apollo::perception::PerceptionObstacle_Type >(perception_object_type_);
}
inline void PlanningObstacle::set_perception_object_type(::apollo::perception::PerceptionObstacle_Type value) {
  
  perception_object_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.perception_object_type)
}

// double prediction_timestamp = 14;
inline void PlanningObstacle::clear_prediction_timestamp() {
  prediction_timestamp_ = 0;
}
inline double PlanningObstacle::prediction_timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.prediction_timestamp)
  return prediction_timestamp_;
}
inline void PlanningObstacle::set_prediction_timestamp(double value) {
  
  prediction_timestamp_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.prediction_timestamp)
}

// repeated .apollo.prediction.Trajectory prediction_trajectory = 15;
inline int PlanningObstacle::prediction_trajectory_size() const {
  return prediction_trajectory_.size();
}
inline ::apollo::prediction::Trajectory* PlanningObstacle::mutable_prediction_trajectory(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningObstacle.prediction_trajectory)
  return prediction_trajectory_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::prediction::Trajectory >*
PlanningObstacle::mutable_prediction_trajectory() {
  // @@protoc_insertion_point(field_mutable_list:apollo.planning_internal.PlanningObstacle.prediction_trajectory)
  return &prediction_trajectory_;
}
inline const ::apollo::prediction::Trajectory& PlanningObstacle::prediction_trajectory(int index) const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.prediction_trajectory)
  return prediction_trajectory_.Get(index);
}
inline ::apollo::prediction::Trajectory* PlanningObstacle::add_prediction_trajectory() {
  // @@protoc_insertion_point(field_add:apollo.planning_internal.PlanningObstacle.prediction_trajectory)
  return prediction_trajectory_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::prediction::Trajectory >&
PlanningObstacle::prediction_trajectory() const {
  // @@protoc_insertion_point(field_list:apollo.planning_internal.PlanningObstacle.prediction_trajectory)
  return prediction_trajectory_;
}

// .apollo.decision.ObjectDecision.ObjectType decision_object_type = 16;
inline void PlanningObstacle::clear_decision_object_type() {
  decision_object_type_ = 0;
}
inline ::apollo::decision::ObjectDecision_ObjectType PlanningObstacle::decision_object_type() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.decision_object_type)
  return static_cast< ::apollo::decision::ObjectDecision_ObjectType >(decision_object_type_);
}
inline void PlanningObstacle::set_decision_object_type(::apollo::decision::ObjectDecision_ObjectType value) {
  
  decision_object_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.PlanningObstacle.decision_object_type)
}

// .apollo.decision.ObjectDecisionType object_decision = 17;
inline bool PlanningObstacle::has_object_decision() const {
  return this != internal_default_instance() && object_decision_ != NULL;
}
inline const ::apollo::decision::ObjectDecisionType& PlanningObstacle::_internal_object_decision() const {
  return *object_decision_;
}
inline const ::apollo::decision::ObjectDecisionType& PlanningObstacle::object_decision() const {
  const ::apollo::decision::ObjectDecisionType* p = object_decision_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.object_decision)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::decision::ObjectDecisionType*>(
      &::apollo::decision::_ObjectDecisionType_default_instance_);
}
inline ::apollo::decision::ObjectDecisionType* PlanningObstacle::release_object_decision() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningObstacle.object_decision)
  
  ::apollo::decision::ObjectDecisionType* temp = object_decision_;
  object_decision_ = NULL;
  return temp;
}
inline ::apollo::decision::ObjectDecisionType* PlanningObstacle::mutable_object_decision() {
  
  if (object_decision_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::decision::ObjectDecisionType>(GetArenaNoVirtual());
    object_decision_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningObstacle.object_decision)
  return object_decision_;
}
inline void PlanningObstacle::set_allocated_object_decision(::apollo::decision::ObjectDecisionType* object_decision) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(object_decision_);
  }
  if (object_decision) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      object_decision = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, object_decision, submessage_arena);
    }
    
  } else {
    
  }
  object_decision_ = object_decision;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningObstacle.object_decision)
}

// repeated .apollo.decision.ObjectDecisionType planning_object_decision = 18;
inline int PlanningObstacle::planning_object_decision_size() const {
  return planning_object_decision_.size();
}
inline ::apollo::decision::ObjectDecisionType* PlanningObstacle::mutable_planning_object_decision(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningObstacle.planning_object_decision)
  return planning_object_decision_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::decision::ObjectDecisionType >*
PlanningObstacle::mutable_planning_object_decision() {
  // @@protoc_insertion_point(field_mutable_list:apollo.planning_internal.PlanningObstacle.planning_object_decision)
  return &planning_object_decision_;
}
inline const ::apollo::decision::ObjectDecisionType& PlanningObstacle::planning_object_decision(int index) const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningObstacle.planning_object_decision)
  return planning_object_decision_.Get(index);
}
inline ::apollo::decision::ObjectDecisionType* PlanningObstacle::add_planning_object_decision() {
  // @@protoc_insertion_point(field_add:apollo.planning_internal.PlanningObstacle.planning_object_decision)
  return planning_object_decision_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::decision::ObjectDecisionType >&
PlanningObstacle::planning_object_decision() const {
  // @@protoc_insertion_point(field_list:apollo.planning_internal.PlanningObstacle.planning_object_decision)
  return planning_object_decision_;
}

// -------------------------------------------------------------------

// Debug_DebugMessage

// .apollo.planning_internal.Debug.ErrorCode error_code = 1;
inline void Debug_DebugMessage::clear_error_code() {
  error_code_ = 0;
}
inline ::apollo::planning_internal::Debug_ErrorCode Debug_DebugMessage::error_code() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.DebugMessage.error_code)
  return static_cast< ::apollo::planning_internal::Debug_ErrorCode >(error_code_);
}
inline void Debug_DebugMessage::set_error_code(::apollo::planning_internal::Debug_ErrorCode value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.error_code)
}

// int32 id = 2;
inline void Debug_DebugMessage::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 Debug_DebugMessage::id() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.DebugMessage.id)
  return id_;
}
inline void Debug_DebugMessage::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.id)
}

// string trace = 3;
inline bool Debug_DebugMessage::has_trace() const {
  return debug_string_case() == kTrace;
}
inline void Debug_DebugMessage::set_has_trace() {
  _oneof_case_[0] = kTrace;
}
inline void Debug_DebugMessage::clear_trace() {
  if (has_trace()) {
    debug_string_.trace_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_debug_string();
  }
}
inline const ::std::string& Debug_DebugMessage::trace() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.DebugMessage.trace)
  if (has_trace()) {
    return debug_string_.trace_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void Debug_DebugMessage::set_trace(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.trace)
  if (!has_trace()) {
    clear_debug_string();
    set_has_trace();
    debug_string_.trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.trace_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.trace)
}
#if LANG_CXX11
inline void Debug_DebugMessage::set_trace(::std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.trace)
  if (!has_trace()) {
    clear_debug_string();
    set_has_trace();
    debug_string_.trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.trace_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.planning_internal.Debug.DebugMessage.trace)
}
#endif
inline void Debug_DebugMessage::set_trace(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_trace()) {
    clear_debug_string();
    set_has_trace();
    debug_string_.trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.trace_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.planning_internal.Debug.DebugMessage.trace)
}
inline void Debug_DebugMessage::set_trace(const char* value, size_t size) {
  if (!has_trace()) {
    clear_debug_string();
    set_has_trace();
    debug_string_.trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.trace_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.planning_internal.Debug.DebugMessage.trace)
}
inline ::std::string* Debug_DebugMessage::mutable_trace() {
  if (!has_trace()) {
    clear_debug_string();
    set_has_trace();
    debug_string_.trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.Debug.DebugMessage.trace)
  return debug_string_.trace_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Debug_DebugMessage::release_trace() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.Debug.DebugMessage.trace)
  if (has_trace()) {
    clear_has_debug_string();
    return debug_string_.trace_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void Debug_DebugMessage::set_allocated_trace(::std::string* trace) {
  if (!has_trace()) {
    debug_string_.trace_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_debug_string();
  if (trace != NULL) {
    set_has_trace();
    debug_string_.trace_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), trace);
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.Debug.DebugMessage.trace)
}

// string info = 4;
inline bool Debug_DebugMessage::has_info() const {
  return debug_string_case() == kInfo;
}
inline void Debug_DebugMessage::set_has_info() {
  _oneof_case_[0] = kInfo;
}
inline void Debug_DebugMessage::clear_info() {
  if (has_info()) {
    debug_string_.info_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_debug_string();
  }
}
inline const ::std::string& Debug_DebugMessage::info() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.DebugMessage.info)
  if (has_info()) {
    return debug_string_.info_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void Debug_DebugMessage::set_info(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.info)
  if (!has_info()) {
    clear_debug_string();
    set_has_info();
    debug_string_.info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.info)
}
#if LANG_CXX11
inline void Debug_DebugMessage::set_info(::std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.info)
  if (!has_info()) {
    clear_debug_string();
    set_has_info();
    debug_string_.info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.planning_internal.Debug.DebugMessage.info)
}
#endif
inline void Debug_DebugMessage::set_info(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_info()) {
    clear_debug_string();
    set_has_info();
    debug_string_.info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.planning_internal.Debug.DebugMessage.info)
}
inline void Debug_DebugMessage::set_info(const char* value, size_t size) {
  if (!has_info()) {
    clear_debug_string();
    set_has_info();
    debug_string_.info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.info_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.planning_internal.Debug.DebugMessage.info)
}
inline ::std::string* Debug_DebugMessage::mutable_info() {
  if (!has_info()) {
    clear_debug_string();
    set_has_info();
    debug_string_.info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.Debug.DebugMessage.info)
  return debug_string_.info_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Debug_DebugMessage::release_info() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.Debug.DebugMessage.info)
  if (has_info()) {
    clear_has_debug_string();
    return debug_string_.info_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void Debug_DebugMessage::set_allocated_info(::std::string* info) {
  if (!has_info()) {
    debug_string_.info_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_debug_string();
  if (info != NULL) {
    set_has_info();
    debug_string_.info_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), info);
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.Debug.DebugMessage.info)
}

// string warn = 5;
inline bool Debug_DebugMessage::has_warn() const {
  return debug_string_case() == kWarn;
}
inline void Debug_DebugMessage::set_has_warn() {
  _oneof_case_[0] = kWarn;
}
inline void Debug_DebugMessage::clear_warn() {
  if (has_warn()) {
    debug_string_.warn_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_debug_string();
  }
}
inline const ::std::string& Debug_DebugMessage::warn() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.DebugMessage.warn)
  if (has_warn()) {
    return debug_string_.warn_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void Debug_DebugMessage::set_warn(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.warn)
  if (!has_warn()) {
    clear_debug_string();
    set_has_warn();
    debug_string_.warn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.warn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.warn)
}
#if LANG_CXX11
inline void Debug_DebugMessage::set_warn(::std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.warn)
  if (!has_warn()) {
    clear_debug_string();
    set_has_warn();
    debug_string_.warn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.warn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.planning_internal.Debug.DebugMessage.warn)
}
#endif
inline void Debug_DebugMessage::set_warn(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_warn()) {
    clear_debug_string();
    set_has_warn();
    debug_string_.warn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.warn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.planning_internal.Debug.DebugMessage.warn)
}
inline void Debug_DebugMessage::set_warn(const char* value, size_t size) {
  if (!has_warn()) {
    clear_debug_string();
    set_has_warn();
    debug_string_.warn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.warn_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.planning_internal.Debug.DebugMessage.warn)
}
inline ::std::string* Debug_DebugMessage::mutable_warn() {
  if (!has_warn()) {
    clear_debug_string();
    set_has_warn();
    debug_string_.warn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.Debug.DebugMessage.warn)
  return debug_string_.warn_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Debug_DebugMessage::release_warn() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.Debug.DebugMessage.warn)
  if (has_warn()) {
    clear_has_debug_string();
    return debug_string_.warn_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void Debug_DebugMessage::set_allocated_warn(::std::string* warn) {
  if (!has_warn()) {
    debug_string_.warn_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_debug_string();
  if (warn != NULL) {
    set_has_warn();
    debug_string_.warn_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), warn);
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.Debug.DebugMessage.warn)
}

// string error = 6;
inline bool Debug_DebugMessage::has_error() const {
  return debug_string_case() == kError;
}
inline void Debug_DebugMessage::set_has_error() {
  _oneof_case_[0] = kError;
}
inline void Debug_DebugMessage::clear_error() {
  if (has_error()) {
    debug_string_.error_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_debug_string();
  }
}
inline const ::std::string& Debug_DebugMessage::error() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.DebugMessage.error)
  if (has_error()) {
    return debug_string_.error_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void Debug_DebugMessage::set_error(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.error)
  if (!has_error()) {
    clear_debug_string();
    set_has_error();
    debug_string_.error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.error)
}
#if LANG_CXX11
inline void Debug_DebugMessage::set_error(::std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.error)
  if (!has_error()) {
    clear_debug_string();
    set_has_error();
    debug_string_.error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.planning_internal.Debug.DebugMessage.error)
}
#endif
inline void Debug_DebugMessage::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_error()) {
    clear_debug_string();
    set_has_error();
    debug_string_.error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.planning_internal.Debug.DebugMessage.error)
}
inline void Debug_DebugMessage::set_error(const char* value, size_t size) {
  if (!has_error()) {
    clear_debug_string();
    set_has_error();
    debug_string_.error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.planning_internal.Debug.DebugMessage.error)
}
inline ::std::string* Debug_DebugMessage::mutable_error() {
  if (!has_error()) {
    clear_debug_string();
    set_has_error();
    debug_string_.error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.Debug.DebugMessage.error)
  return debug_string_.error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Debug_DebugMessage::release_error() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.Debug.DebugMessage.error)
  if (has_error()) {
    clear_has_debug_string();
    return debug_string_.error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void Debug_DebugMessage::set_allocated_error(::std::string* error) {
  if (!has_error()) {
    debug_string_.error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_debug_string();
  if (error != NULL) {
    set_has_error();
    debug_string_.error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.Debug.DebugMessage.error)
}

// string fatal = 7;
inline bool Debug_DebugMessage::has_fatal() const {
  return debug_string_case() == kFatal;
}
inline void Debug_DebugMessage::set_has_fatal() {
  _oneof_case_[0] = kFatal;
}
inline void Debug_DebugMessage::clear_fatal() {
  if (has_fatal()) {
    debug_string_.fatal_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_debug_string();
  }
}
inline const ::std::string& Debug_DebugMessage::fatal() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.DebugMessage.fatal)
  if (has_fatal()) {
    return debug_string_.fatal_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void Debug_DebugMessage::set_fatal(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.fatal)
  if (!has_fatal()) {
    clear_debug_string();
    set_has_fatal();
    debug_string_.fatal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.fatal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.fatal)
}
#if LANG_CXX11
inline void Debug_DebugMessage::set_fatal(::std::string&& value) {
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.DebugMessage.fatal)
  if (!has_fatal()) {
    clear_debug_string();
    set_has_fatal();
    debug_string_.fatal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.fatal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.planning_internal.Debug.DebugMessage.fatal)
}
#endif
inline void Debug_DebugMessage::set_fatal(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_fatal()) {
    clear_debug_string();
    set_has_fatal();
    debug_string_.fatal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.fatal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.planning_internal.Debug.DebugMessage.fatal)
}
inline void Debug_DebugMessage::set_fatal(const char* value, size_t size) {
  if (!has_fatal()) {
    clear_debug_string();
    set_has_fatal();
    debug_string_.fatal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  debug_string_.fatal_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.planning_internal.Debug.DebugMessage.fatal)
}
inline ::std::string* Debug_DebugMessage::mutable_fatal() {
  if (!has_fatal()) {
    clear_debug_string();
    set_has_fatal();
    debug_string_.fatal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.Debug.DebugMessage.fatal)
  return debug_string_.fatal_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Debug_DebugMessage::release_fatal() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.Debug.DebugMessage.fatal)
  if (has_fatal()) {
    clear_has_debug_string();
    return debug_string_.fatal_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void Debug_DebugMessage::set_allocated_fatal(::std::string* fatal) {
  if (!has_fatal()) {
    debug_string_.fatal_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_debug_string();
  if (fatal != NULL) {
    set_has_fatal();
    debug_string_.fatal_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fatal);
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.Debug.DebugMessage.fatal)
}

inline bool Debug_DebugMessage::has_debug_string() const {
  return debug_string_case() != DEBUG_STRING_NOT_SET;
}
inline void Debug_DebugMessage::clear_has_debug_string() {
  _oneof_case_[0] = DEBUG_STRING_NOT_SET;
}
inline Debug_DebugMessage::DebugStringCase Debug_DebugMessage::debug_string_case() const {
  return Debug_DebugMessage::DebugStringCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Debug

// .apollo.planning_internal.Debug.ErrorCode error_code = 1;
inline void Debug::clear_error_code() {
  error_code_ = 0;
}
inline ::apollo::planning_internal::Debug_ErrorCode Debug::error_code() const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.error_code)
  return static_cast< ::apollo::planning_internal::Debug_ErrorCode >(error_code_);
}
inline void Debug::set_error_code(::apollo::planning_internal::Debug_ErrorCode value) {
  
  error_code_ = value;
  // @@protoc_insertion_point(field_set:apollo.planning_internal.Debug.error_code)
}

// .apollo.planning_internal.PlanningData planning_data = 2;
inline bool Debug::has_planning_data() const {
  return this != internal_default_instance() && planning_data_ != NULL;
}
inline void Debug::clear_planning_data() {
  if (GetArenaNoVirtual() == NULL && planning_data_ != NULL) {
    delete planning_data_;
  }
  planning_data_ = NULL;
}
inline const ::apollo::planning_internal::PlanningData& Debug::_internal_planning_data() const {
  return *planning_data_;
}
inline const ::apollo::planning_internal::PlanningData& Debug::planning_data() const {
  const ::apollo::planning_internal::PlanningData* p = planning_data_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.planning_data)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::planning_internal::PlanningData*>(
      &::apollo::planning_internal::_PlanningData_default_instance_);
}
inline ::apollo::planning_internal::PlanningData* Debug::release_planning_data() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.Debug.planning_data)
  
  ::apollo::planning_internal::PlanningData* temp = planning_data_;
  planning_data_ = NULL;
  return temp;
}
inline ::apollo::planning_internal::PlanningData* Debug::mutable_planning_data() {
  
  if (planning_data_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::planning_internal::PlanningData>(GetArenaNoVirtual());
    planning_data_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.Debug.planning_data)
  return planning_data_;
}
inline void Debug::set_allocated_planning_data(::apollo::planning_internal::PlanningData* planning_data) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete planning_data_;
  }
  if (planning_data) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      planning_data = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, planning_data, submessage_arena);
    }
    
  } else {
    
  }
  planning_data_ = planning_data;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.Debug.planning_data)
}

// repeated .apollo.planning_internal.Debug.DebugMessage debug_message = 3;
inline int Debug::debug_message_size() const {
  return debug_message_.size();
}
inline void Debug::clear_debug_message() {
  debug_message_.Clear();
}
inline ::apollo::planning_internal::Debug_DebugMessage* Debug::mutable_debug_message(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.Debug.debug_message)
  return debug_message_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::Debug_DebugMessage >*
Debug::mutable_debug_message() {
  // @@protoc_insertion_point(field_mutable_list:apollo.planning_internal.Debug.debug_message)
  return &debug_message_;
}
inline const ::apollo::planning_internal::Debug_DebugMessage& Debug::debug_message(int index) const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.Debug.debug_message)
  return debug_message_.Get(index);
}
inline ::apollo::planning_internal::Debug_DebugMessage* Debug::add_debug_message() {
  // @@protoc_insertion_point(field_add:apollo.planning_internal.Debug.debug_message)
  return debug_message_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::Debug_DebugMessage >&
Debug::debug_message() const {
  // @@protoc_insertion_point(field_list:apollo.planning_internal.Debug.debug_message)
  return debug_message_;
}

// -------------------------------------------------------------------

// PlanningData

// .apollo.common.Header header = 1;
inline bool PlanningData::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::apollo::common::Header& PlanningData::_internal_header() const {
  return *header_;
}
inline const ::apollo::common::Header& PlanningData::header() const {
  const ::apollo::common::Header* p = header_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningData.header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* PlanningData::release_header() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningData.header)
  
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::apollo::common::Header* PlanningData::mutable_header() {
  
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningData.header)
  return header_;
}
inline void PlanningData::set_allocated_header(::apollo::common::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningData.header)
}

// .apollo.localization.Pose init_status = 2;
inline bool PlanningData::has_init_status() const {
  return this != internal_default_instance() && init_status_ != NULL;
}
inline const ::apollo::localization::Pose& PlanningData::_internal_init_status() const {
  return *init_status_;
}
inline const ::apollo::localization::Pose& PlanningData::init_status() const {
  const ::apollo::localization::Pose* p = init_status_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningData.init_status)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::localization::Pose*>(
      &::apollo::localization::_Pose_default_instance_);
}
inline ::apollo::localization::Pose* PlanningData::release_init_status() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningData.init_status)
  
  ::apollo::localization::Pose* temp = init_status_;
  init_status_ = NULL;
  return temp;
}
inline ::apollo::localization::Pose* PlanningData::mutable_init_status() {
  
  if (init_status_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::localization::Pose>(GetArenaNoVirtual());
    init_status_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningData.init_status)
  return init_status_;
}
inline void PlanningData::set_allocated_init_status(::apollo::localization::Pose* init_status) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(init_status_);
  }
  if (init_status) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      init_status = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, init_status, submessage_arena);
    }
    
  } else {
    
  }
  init_status_ = init_status;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningData.init_status)
}

// .apollo.decision.MainDecision main_decision = 3;
inline bool PlanningData::has_main_decision() const {
  return this != internal_default_instance() && main_decision_ != NULL;
}
inline const ::apollo::decision::MainDecision& PlanningData::_internal_main_decision() const {
  return *main_decision_;
}
inline const ::apollo::decision::MainDecision& PlanningData::main_decision() const {
  const ::apollo::decision::MainDecision* p = main_decision_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningData.main_decision)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::decision::MainDecision*>(
      &::apollo::decision::_MainDecision_default_instance_);
}
inline ::apollo::decision::MainDecision* PlanningData::release_main_decision() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningData.main_decision)
  
  ::apollo::decision::MainDecision* temp = main_decision_;
  main_decision_ = NULL;
  return temp;
}
inline ::apollo::decision::MainDecision* PlanningData::mutable_main_decision() {
  
  if (main_decision_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::decision::MainDecision>(GetArenaNoVirtual());
    main_decision_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningData.main_decision)
  return main_decision_;
}
inline void PlanningData::set_allocated_main_decision(::apollo::decision::MainDecision* main_decision) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(main_decision_);
  }
  if (main_decision) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      main_decision = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, main_decision, submessage_arena);
    }
    
  } else {
    
  }
  main_decision_ = main_decision;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningData.main_decision)
}

// repeated .apollo.planning_internal.PlanningObstacle planning_obstacle = 4;
inline int PlanningData::planning_obstacle_size() const {
  return planning_obstacle_.size();
}
inline void PlanningData::clear_planning_obstacle() {
  planning_obstacle_.Clear();
}
inline ::apollo::planning_internal::PlanningObstacle* PlanningData::mutable_planning_obstacle(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningData.planning_obstacle)
  return planning_obstacle_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::PlanningObstacle >*
PlanningData::mutable_planning_obstacle() {
  // @@protoc_insertion_point(field_mutable_list:apollo.planning_internal.PlanningData.planning_obstacle)
  return &planning_obstacle_;
}
inline const ::apollo::planning_internal::PlanningObstacle& PlanningData::planning_obstacle(int index) const {
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningData.planning_obstacle)
  return planning_obstacle_.Get(index);
}
inline ::apollo::planning_internal::PlanningObstacle* PlanningData::add_planning_obstacle() {
  // @@protoc_insertion_point(field_add:apollo.planning_internal.PlanningData.planning_obstacle)
  return planning_obstacle_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::planning_internal::PlanningObstacle >&
PlanningData::planning_obstacle() const {
  // @@protoc_insertion_point(field_list:apollo.planning_internal.PlanningData.planning_obstacle)
  return planning_obstacle_;
}

// .apollo.decision.LightSignal light_signal = 5;
inline bool PlanningData::has_light_signal() const {
  return this != internal_default_instance() && light_signal_ != NULL;
}
inline const ::apollo::decision::LightSignal& PlanningData::_internal_light_signal() const {
  return *light_signal_;
}
inline const ::apollo::decision::LightSignal& PlanningData::light_signal() const {
  const ::apollo::decision::LightSignal* p = light_signal_;
  // @@protoc_insertion_point(field_get:apollo.planning_internal.PlanningData.light_signal)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::decision::LightSignal*>(
      &::apollo::decision::_LightSignal_default_instance_);
}
inline ::apollo::decision::LightSignal* PlanningData::release_light_signal() {
  // @@protoc_insertion_point(field_release:apollo.planning_internal.PlanningData.light_signal)
  
  ::apollo::decision::LightSignal* temp = light_signal_;
  light_signal_ = NULL;
  return temp;
}
inline ::apollo::decision::LightSignal* PlanningData::mutable_light_signal() {
  
  if (light_signal_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::decision::LightSignal>(GetArenaNoVirtual());
    light_signal_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.planning_internal.PlanningData.light_signal)
  return light_signal_;
}
inline void PlanningData::set_allocated_light_signal(::apollo::decision::LightSignal* light_signal) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(light_signal_);
  }
  if (light_signal) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      light_signal = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, light_signal, submessage_arena);
    }
    
  } else {
    
  }
  light_signal_ = light_signal;
  // @@protoc_insertion_point(field_set_allocated:apollo.planning_internal.PlanningData.light_signal)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace planning_internal
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::planning_internal::Debug_ErrorCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::planning_internal::Debug_ErrorCode>() {
  return ::apollo::planning_internal::Debug_ErrorCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2fplanning_2fplanning_5finternal_2eproto
