// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apollo_msgs/proto/control/control_cmd.proto

#ifndef PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto
#define PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "apollo_msgs/proto/canbus/chassis.pb.h"
#include "apollo_msgs/proto/common/header.pb.h"
#include "apollo_msgs/proto/control/pad_msg.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto 

namespace protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto
namespace apollo {
namespace control {
class ControlCommand;
class ControlCommandDefaultTypeInternal;
extern ControlCommandDefaultTypeInternal _ControlCommand_default_instance_;
class Debug;
class DebugDefaultTypeInternal;
extern DebugDefaultTypeInternal _Debug_default_instance_;
class InputDebug;
class InputDebugDefaultTypeInternal;
extern InputDebugDefaultTypeInternal _InputDebug_default_instance_;
class LatencyStats;
class LatencyStatsDefaultTypeInternal;
extern LatencyStatsDefaultTypeInternal _LatencyStats_default_instance_;
class SimpleLateralDebug;
class SimpleLateralDebugDefaultTypeInternal;
extern SimpleLateralDebugDefaultTypeInternal _SimpleLateralDebug_default_instance_;
class SimpleLongitudinalDebug;
class SimpleLongitudinalDebugDefaultTypeInternal;
extern SimpleLongitudinalDebugDefaultTypeInternal _SimpleLongitudinalDebug_default_instance_;
}  // namespace control
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::control::ControlCommand* Arena::CreateMaybeMessage<::apollo::control::ControlCommand>(Arena*);
template<> ::apollo::control::Debug* Arena::CreateMaybeMessage<::apollo::control::Debug>(Arena*);
template<> ::apollo::control::InputDebug* Arena::CreateMaybeMessage<::apollo::control::InputDebug>(Arena*);
template<> ::apollo::control::LatencyStats* Arena::CreateMaybeMessage<::apollo::control::LatencyStats>(Arena*);
template<> ::apollo::control::SimpleLateralDebug* Arena::CreateMaybeMessage<::apollo::control::SimpleLateralDebug>(Arena*);
template<> ::apollo::control::SimpleLongitudinalDebug* Arena::CreateMaybeMessage<::apollo::control::SimpleLongitudinalDebug>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace control {

enum TurnSignal {
  TURN_NONE = 0,
  TURN_LEFT = 1,
  TURN_RIGHT = 2,
  TurnSignal_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  TurnSignal_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool TurnSignal_IsValid(int value);
const TurnSignal TurnSignal_MIN = TURN_NONE;
const TurnSignal TurnSignal_MAX = TURN_RIGHT;
const int TurnSignal_ARRAYSIZE = TurnSignal_MAX + 1;

const ::google::protobuf::EnumDescriptor* TurnSignal_descriptor();
inline const ::std::string& TurnSignal_Name(TurnSignal value) {
  return ::google::protobuf::internal::NameOfEnum(
    TurnSignal_descriptor(), value);
}
inline bool TurnSignal_Parse(
    const ::std::string& name, TurnSignal* value) {
  return ::google::protobuf::internal::ParseNamedEnum<TurnSignal>(
    TurnSignal_descriptor(), name, value);
}
// ===================================================================

class LatencyStats : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.control.LatencyStats) */ {
 public:
  LatencyStats();
  virtual ~LatencyStats();

  LatencyStats(const LatencyStats& from);

  inline LatencyStats& operator=(const LatencyStats& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LatencyStats(LatencyStats&& from) noexcept
    : LatencyStats() {
    *this = ::std::move(from);
  }

  inline LatencyStats& operator=(LatencyStats&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LatencyStats& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LatencyStats* internal_default_instance() {
    return reinterpret_cast<const LatencyStats*>(
               &_LatencyStats_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(LatencyStats* other);
  friend void swap(LatencyStats& a, LatencyStats& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LatencyStats* New() const final {
    return CreateMaybeMessage<LatencyStats>(NULL);
  }

  LatencyStats* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LatencyStats>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LatencyStats& from);
  void MergeFrom(const LatencyStats& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LatencyStats* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated double controller_time_ms = 2;
  int controller_time_ms_size() const;
  void clear_controller_time_ms();
  static const int kControllerTimeMsFieldNumber = 2;
  double controller_time_ms(int index) const;
  void set_controller_time_ms(int index, double value);
  void add_controller_time_ms(double value);
  const ::google::protobuf::RepeatedField< double >&
      controller_time_ms() const;
  ::google::protobuf::RepeatedField< double >*
      mutable_controller_time_ms();

  // double total_time_ms = 1;
  void clear_total_time_ms();
  static const int kTotalTimeMsFieldNumber = 1;
  double total_time_ms() const;
  void set_total_time_ms(double value);

  // @@protoc_insertion_point(class_scope:apollo.control.LatencyStats)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< double > controller_time_ms_;
  mutable int _controller_time_ms_cached_byte_size_;
  double total_time_ms_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ControlCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.control.ControlCommand) */ {
 public:
  ControlCommand();
  virtual ~ControlCommand();

  ControlCommand(const ControlCommand& from);

  inline ControlCommand& operator=(const ControlCommand& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ControlCommand(ControlCommand&& from) noexcept
    : ControlCommand() {
    *this = ::std::move(from);
  }

  inline ControlCommand& operator=(ControlCommand&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ControlCommand& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ControlCommand* internal_default_instance() {
    return reinterpret_cast<const ControlCommand*>(
               &_ControlCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ControlCommand* other);
  friend void swap(ControlCommand& a, ControlCommand& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ControlCommand* New() const final {
    return CreateMaybeMessage<ControlCommand>(NULL);
  }

  ControlCommand* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ControlCommand>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ControlCommand& from);
  void MergeFrom(const ControlCommand& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::apollo::common::Header& _internal_header() const;
  public:
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* release_header();
  ::apollo::common::Header* mutable_header();
  void set_allocated_header(::apollo::common::Header* header);

  // .apollo.control.Debug debug = 22;
  bool has_debug() const;
  void clear_debug();
  static const int kDebugFieldNumber = 22;
  private:
  const ::apollo::control::Debug& _internal_debug() const;
  public:
  const ::apollo::control::Debug& debug() const;
  ::apollo::control::Debug* release_debug();
  ::apollo::control::Debug* mutable_debug();
  void set_allocated_debug(::apollo::control::Debug* debug);

  // .apollo.canbus.Signal signal = 23;
  bool has_signal() const;
  void clear_signal();
  static const int kSignalFieldNumber = 23;
  private:
  const ::apollo::canbus::Signal& _internal_signal() const;
  public:
  const ::apollo::canbus::Signal& signal() const;
  ::apollo::canbus::Signal* release_signal();
  ::apollo::canbus::Signal* mutable_signal();
  void set_allocated_signal(::apollo::canbus::Signal* signal);

  // .apollo.control.LatencyStats latency_stats = 24;
  bool has_latency_stats() const;
  void clear_latency_stats();
  static const int kLatencyStatsFieldNumber = 24;
  private:
  const ::apollo::control::LatencyStats& _internal_latency_stats() const;
  public:
  const ::apollo::control::LatencyStats& latency_stats() const;
  ::apollo::control::LatencyStats* release_latency_stats();
  ::apollo::control::LatencyStats* mutable_latency_stats();
  void set_allocated_latency_stats(::apollo::control::LatencyStats* latency_stats);

  // .apollo.control.PadMessage pad_msg = 25;
  bool has_pad_msg() const;
  void clear_pad_msg();
  static const int kPadMsgFieldNumber = 25;
  private:
  const ::apollo::control::PadMessage& _internal_pad_msg() const;
  public:
  const ::apollo::control::PadMessage& pad_msg() const;
  ::apollo::control::PadMessage* release_pad_msg();
  ::apollo::control::PadMessage* mutable_pad_msg();
  void set_allocated_pad_msg(::apollo::control::PadMessage* pad_msg);

  // double throttle = 3;
  void clear_throttle();
  static const int kThrottleFieldNumber = 3;
  double throttle() const;
  void set_throttle(double value);

  // double brake = 4;
  void clear_brake();
  static const int kBrakeFieldNumber = 4;
  double brake() const;
  void set_brake(double value);

  // double steering_rate = 6;
  void clear_steering_rate();
  static const int kSteeringRateFieldNumber = 6;
  double steering_rate() const;
  void set_steering_rate(double value);

  // double steering_target = 7;
  void clear_steering_target();
  static const int kSteeringTargetFieldNumber = 7;
  double steering_target() const;
  void set_steering_target(double value);

  // double speed = 9;
  void clear_speed();
  static const int kSpeedFieldNumber = 9;
  double speed() const;
  void set_speed(double value);

  // double acceleration = 10;
  void clear_acceleration();
  static const int kAccelerationFieldNumber = 10;
  double acceleration() const;
  void set_acceleration(double value);

  // bool right_turn = 14;
  void clear_right_turn();
  static const int kRightTurnFieldNumber = 14;
  bool right_turn() const;
  void set_right_turn(bool value);

  // bool high_beam = 11;
  void clear_high_beam();
  static const int kHighBeamFieldNumber = 11;
  bool high_beam() const;
  void set_high_beam(bool value);

  // bool low_beam = 12;
  void clear_low_beam();
  static const int kLowBeamFieldNumber = 12;
  bool low_beam() const;
  void set_low_beam(bool value);

  // bool horn = 15;
  void clear_horn();
  static const int kHornFieldNumber = 15;
  bool horn() const;
  void set_horn(bool value);

  // bool parking_brake = 8;
  void clear_parking_brake();
  static const int kParkingBrakeFieldNumber = 8;
  bool parking_brake() const;
  void set_parking_brake(bool value);

  // bool reset_model = 16;
  void clear_reset_model();
  static const int kResetModelFieldNumber = 16;
  bool reset_model() const;
  void set_reset_model(bool value);

  // bool engine_on_off = 17;
  void clear_engine_on_off();
  static const int kEngineOnOffFieldNumber = 17;
  bool engine_on_off() const;
  void set_engine_on_off(bool value);

  // bool left_turn = 13;
  void clear_left_turn();
  static const int kLeftTurnFieldNumber = 13;
  bool left_turn() const;
  void set_left_turn(bool value);

  // double trajectory_fraction = 18;
  void clear_trajectory_fraction();
  static const int kTrajectoryFractionFieldNumber = 18;
  double trajectory_fraction() const;
  void set_trajectory_fraction(double value);

  // .apollo.canbus.Chassis.DrivingMode driving_mode = 19;
  void clear_driving_mode();
  static const int kDrivingModeFieldNumber = 19;
  ::apollo::canbus::Chassis_DrivingMode driving_mode() const;
  void set_driving_mode(::apollo::canbus::Chassis_DrivingMode value);

  // .apollo.canbus.Chassis.GearPosition gear_location = 20;
  void clear_gear_location();
  static const int kGearLocationFieldNumber = 20;
  ::apollo::canbus::Chassis_GearPosition gear_location() const;
  void set_gear_location(::apollo::canbus::Chassis_GearPosition value);

  // .apollo.control.TurnSignal turnsignal = 21;
  void clear_turnsignal();
  static const int kTurnsignalFieldNumber = 21;
  ::apollo::control::TurnSignal turnsignal() const;
  void set_turnsignal(::apollo::control::TurnSignal value);

  // @@protoc_insertion_point(class_scope:apollo.control.ControlCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::apollo::common::Header* header_;
  ::apollo::control::Debug* debug_;
  ::apollo::canbus::Signal* signal_;
  ::apollo::control::LatencyStats* latency_stats_;
  ::apollo::control::PadMessage* pad_msg_;
  double throttle_;
  double brake_;
  double steering_rate_;
  double steering_target_;
  double speed_;
  double acceleration_;
  bool right_turn_;
  bool high_beam_;
  bool low_beam_;
  bool horn_;
  bool parking_brake_;
  bool reset_model_;
  bool engine_on_off_;
  bool left_turn_;
  double trajectory_fraction_;
  int driving_mode_;
  int gear_location_;
  int turnsignal_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimpleLongitudinalDebug : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.control.SimpleLongitudinalDebug) */ {
 public:
  SimpleLongitudinalDebug();
  virtual ~SimpleLongitudinalDebug();

  SimpleLongitudinalDebug(const SimpleLongitudinalDebug& from);

  inline SimpleLongitudinalDebug& operator=(const SimpleLongitudinalDebug& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SimpleLongitudinalDebug(SimpleLongitudinalDebug&& from) noexcept
    : SimpleLongitudinalDebug() {
    *this = ::std::move(from);
  }

  inline SimpleLongitudinalDebug& operator=(SimpleLongitudinalDebug&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SimpleLongitudinalDebug& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SimpleLongitudinalDebug* internal_default_instance() {
    return reinterpret_cast<const SimpleLongitudinalDebug*>(
               &_SimpleLongitudinalDebug_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SimpleLongitudinalDebug* other);
  friend void swap(SimpleLongitudinalDebug& a, SimpleLongitudinalDebug& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SimpleLongitudinalDebug* New() const final {
    return CreateMaybeMessage<SimpleLongitudinalDebug>(NULL);
  }

  SimpleLongitudinalDebug* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SimpleLongitudinalDebug>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SimpleLongitudinalDebug& from);
  void MergeFrom(const SimpleLongitudinalDebug& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimpleLongitudinalDebug* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double station_reference = 1;
  void clear_station_reference();
  static const int kStationReferenceFieldNumber = 1;
  double station_reference() const;
  void set_station_reference(double value);

  // double station_error = 2;
  void clear_station_error();
  static const int kStationErrorFieldNumber = 2;
  double station_error() const;
  void set_station_error(double value);

  // double station_error_limited = 3;
  void clear_station_error_limited();
  static const int kStationErrorLimitedFieldNumber = 3;
  double station_error_limited() const;
  void set_station_error_limited(double value);

  // double preview_station_error = 4;
  void clear_preview_station_error();
  static const int kPreviewStationErrorFieldNumber = 4;
  double preview_station_error() const;
  void set_preview_station_error(double value);

  // double speed_reference = 5;
  void clear_speed_reference();
  static const int kSpeedReferenceFieldNumber = 5;
  double speed_reference() const;
  void set_speed_reference(double value);

  // double speed_error = 6;
  void clear_speed_error();
  static const int kSpeedErrorFieldNumber = 6;
  double speed_error() const;
  void set_speed_error(double value);

  // double speed_controller_input_limited = 7;
  void clear_speed_controller_input_limited();
  static const int kSpeedControllerInputLimitedFieldNumber = 7;
  double speed_controller_input_limited() const;
  void set_speed_controller_input_limited(double value);

  // double preview_speed_reference = 8;
  void clear_preview_speed_reference();
  static const int kPreviewSpeedReferenceFieldNumber = 8;
  double preview_speed_reference() const;
  void set_preview_speed_reference(double value);

  // double preview_speed_error = 9;
  void clear_preview_speed_error();
  static const int kPreviewSpeedErrorFieldNumber = 9;
  double preview_speed_error() const;
  void set_preview_speed_error(double value);

  // double preview_acceleration_reference = 10;
  void clear_preview_acceleration_reference();
  static const int kPreviewAccelerationReferenceFieldNumber = 10;
  double preview_acceleration_reference() const;
  void set_preview_acceleration_reference(double value);

  // double acceleration_cmd_closeloop = 11;
  void clear_acceleration_cmd_closeloop();
  static const int kAccelerationCmdCloseloopFieldNumber = 11;
  double acceleration_cmd_closeloop() const;
  void set_acceleration_cmd_closeloop(double value);

  // double acceleration_cmd = 12;
  void clear_acceleration_cmd();
  static const int kAccelerationCmdFieldNumber = 12;
  double acceleration_cmd() const;
  void set_acceleration_cmd(double value);

  // double acceleration_lookup = 13;
  void clear_acceleration_lookup();
  static const int kAccelerationLookupFieldNumber = 13;
  double acceleration_lookup() const;
  void set_acceleration_lookup(double value);

  // double speed_lookup = 14;
  void clear_speed_lookup();
  static const int kSpeedLookupFieldNumber = 14;
  double speed_lookup() const;
  void set_speed_lookup(double value);

  // double calibration_value = 15;
  void clear_calibration_value();
  static const int kCalibrationValueFieldNumber = 15;
  double calibration_value() const;
  void set_calibration_value(double value);

  // double throttle_cmd = 16;
  void clear_throttle_cmd();
  static const int kThrottleCmdFieldNumber = 16;
  double throttle_cmd() const;
  void set_throttle_cmd(double value);

  // double brake_cmd = 17;
  void clear_brake_cmd();
  static const int kBrakeCmdFieldNumber = 17;
  double brake_cmd() const;
  void set_brake_cmd(double value);

  // bool is_full_stop = 18;
  void clear_is_full_stop();
  static const int kIsFullStopFieldNumber = 18;
  bool is_full_stop() const;
  void set_is_full_stop(bool value);

  // @@protoc_insertion_point(class_scope:apollo.control.SimpleLongitudinalDebug)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double station_reference_;
  double station_error_;
  double station_error_limited_;
  double preview_station_error_;
  double speed_reference_;
  double speed_error_;
  double speed_controller_input_limited_;
  double preview_speed_reference_;
  double preview_speed_error_;
  double preview_acceleration_reference_;
  double acceleration_cmd_closeloop_;
  double acceleration_cmd_;
  double acceleration_lookup_;
  double speed_lookup_;
  double calibration_value_;
  double throttle_cmd_;
  double brake_cmd_;
  bool is_full_stop_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SimpleLateralDebug : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.control.SimpleLateralDebug) */ {
 public:
  SimpleLateralDebug();
  virtual ~SimpleLateralDebug();

  SimpleLateralDebug(const SimpleLateralDebug& from);

  inline SimpleLateralDebug& operator=(const SimpleLateralDebug& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SimpleLateralDebug(SimpleLateralDebug&& from) noexcept
    : SimpleLateralDebug() {
    *this = ::std::move(from);
  }

  inline SimpleLateralDebug& operator=(SimpleLateralDebug&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SimpleLateralDebug& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SimpleLateralDebug* internal_default_instance() {
    return reinterpret_cast<const SimpleLateralDebug*>(
               &_SimpleLateralDebug_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(SimpleLateralDebug* other);
  friend void swap(SimpleLateralDebug& a, SimpleLateralDebug& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SimpleLateralDebug* New() const final {
    return CreateMaybeMessage<SimpleLateralDebug>(NULL);
  }

  SimpleLateralDebug* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SimpleLateralDebug>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SimpleLateralDebug& from);
  void MergeFrom(const SimpleLateralDebug& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SimpleLateralDebug* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double lateral_error = 1;
  void clear_lateral_error();
  static const int kLateralErrorFieldNumber = 1;
  double lateral_error() const;
  void set_lateral_error(double value);

  // double ref_heading = 2;
  void clear_ref_heading();
  static const int kRefHeadingFieldNumber = 2;
  double ref_heading() const;
  void set_ref_heading(double value);

  // double heading = 3;
  void clear_heading();
  static const int kHeadingFieldNumber = 3;
  double heading() const;
  void set_heading(double value);

  // double heading_error = 4;
  void clear_heading_error();
  static const int kHeadingErrorFieldNumber = 4;
  double heading_error() const;
  void set_heading_error(double value);

  // double heading_error_rate = 5;
  void clear_heading_error_rate();
  static const int kHeadingErrorRateFieldNumber = 5;
  double heading_error_rate() const;
  void set_heading_error_rate(double value);

  // double lateral_error_rate = 6;
  void clear_lateral_error_rate();
  static const int kLateralErrorRateFieldNumber = 6;
  double lateral_error_rate() const;
  void set_lateral_error_rate(double value);

  // double curvature = 7;
  void clear_curvature();
  static const int kCurvatureFieldNumber = 7;
  double curvature() const;
  void set_curvature(double value);

  // double steer_angle = 8;
  void clear_steer_angle();
  static const int kSteerAngleFieldNumber = 8;
  double steer_angle() const;
  void set_steer_angle(double value);

  // double steer_angle_feedforward = 9;
  void clear_steer_angle_feedforward();
  static const int kSteerAngleFeedforwardFieldNumber = 9;
  double steer_angle_feedforward() const;
  void set_steer_angle_feedforward(double value);

  // double steer_angle_lateral_contribution = 10;
  void clear_steer_angle_lateral_contribution();
  static const int kSteerAngleLateralContributionFieldNumber = 10;
  double steer_angle_lateral_contribution() const;
  void set_steer_angle_lateral_contribution(double value);

  // double steer_angle_lateral_rate_contribution = 11;
  void clear_steer_angle_lateral_rate_contribution();
  static const int kSteerAngleLateralRateContributionFieldNumber = 11;
  double steer_angle_lateral_rate_contribution() const;
  void set_steer_angle_lateral_rate_contribution(double value);

  // double steer_angle_heading_contribution = 12;
  void clear_steer_angle_heading_contribution();
  static const int kSteerAngleHeadingContributionFieldNumber = 12;
  double steer_angle_heading_contribution() const;
  void set_steer_angle_heading_contribution(double value);

  // double steer_angle_heading_rate_contribution = 13;
  void clear_steer_angle_heading_rate_contribution();
  static const int kSteerAngleHeadingRateContributionFieldNumber = 13;
  double steer_angle_heading_rate_contribution() const;
  void set_steer_angle_heading_rate_contribution(double value);

  // double steer_angle_feedback = 14;
  void clear_steer_angle_feedback();
  static const int kSteerAngleFeedbackFieldNumber = 14;
  double steer_angle_feedback() const;
  void set_steer_angle_feedback(double value);

  // double steering_position = 15;
  void clear_steering_position();
  static const int kSteeringPositionFieldNumber = 15;
  double steering_position() const;
  void set_steering_position(double value);

  // double ref_speed = 16;
  void clear_ref_speed();
  static const int kRefSpeedFieldNumber = 16;
  double ref_speed() const;
  void set_ref_speed(double value);

  // @@protoc_insertion_point(class_scope:apollo.control.SimpleLateralDebug)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double lateral_error_;
  double ref_heading_;
  double heading_;
  double heading_error_;
  double heading_error_rate_;
  double lateral_error_rate_;
  double curvature_;
  double steer_angle_;
  double steer_angle_feedforward_;
  double steer_angle_lateral_contribution_;
  double steer_angle_lateral_rate_contribution_;
  double steer_angle_heading_contribution_;
  double steer_angle_heading_rate_contribution_;
  double steer_angle_feedback_;
  double steering_position_;
  double ref_speed_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InputDebug : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.control.InputDebug) */ {
 public:
  InputDebug();
  virtual ~InputDebug();

  InputDebug(const InputDebug& from);

  inline InputDebug& operator=(const InputDebug& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InputDebug(InputDebug&& from) noexcept
    : InputDebug() {
    *this = ::std::move(from);
  }

  inline InputDebug& operator=(InputDebug&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InputDebug& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InputDebug* internal_default_instance() {
    return reinterpret_cast<const InputDebug*>(
               &_InputDebug_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(InputDebug* other);
  friend void swap(InputDebug& a, InputDebug& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InputDebug* New() const final {
    return CreateMaybeMessage<InputDebug>(NULL);
  }

  InputDebug* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InputDebug>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InputDebug& from);
  void MergeFrom(const InputDebug& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InputDebug* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .apollo.common.Header localization_header = 1;
  bool has_localization_header() const;
  void clear_localization_header();
  static const int kLocalizationHeaderFieldNumber = 1;
  private:
  const ::apollo::common::Header& _internal_localization_header() const;
  public:
  const ::apollo::common::Header& localization_header() const;
  ::apollo::common::Header* release_localization_header();
  ::apollo::common::Header* mutable_localization_header();
  void set_allocated_localization_header(::apollo::common::Header* localization_header);

  // .apollo.common.Header canbus_header = 2;
  bool has_canbus_header() const;
  void clear_canbus_header();
  static const int kCanbusHeaderFieldNumber = 2;
  private:
  const ::apollo::common::Header& _internal_canbus_header() const;
  public:
  const ::apollo::common::Header& canbus_header() const;
  ::apollo::common::Header* release_canbus_header();
  ::apollo::common::Header* mutable_canbus_header();
  void set_allocated_canbus_header(::apollo::common::Header* canbus_header);

  // .apollo.common.Header trajectory_header = 3;
  bool has_trajectory_header() const;
  void clear_trajectory_header();
  static const int kTrajectoryHeaderFieldNumber = 3;
  private:
  const ::apollo::common::Header& _internal_trajectory_header() const;
  public:
  const ::apollo::common::Header& trajectory_header() const;
  ::apollo::common::Header* release_trajectory_header();
  ::apollo::common::Header* mutable_trajectory_header();
  void set_allocated_trajectory_header(::apollo::common::Header* trajectory_header);

  // @@protoc_insertion_point(class_scope:apollo.control.InputDebug)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::apollo::common::Header* localization_header_;
  ::apollo::common::Header* canbus_header_;
  ::apollo::common::Header* trajectory_header_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Debug : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.control.Debug) */ {
 public:
  Debug();
  virtual ~Debug();

  Debug(const Debug& from);

  inline Debug& operator=(const Debug& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Debug(Debug&& from) noexcept
    : Debug() {
    *this = ::std::move(from);
  }

  inline Debug& operator=(Debug&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Debug& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Debug* internal_default_instance() {
    return reinterpret_cast<const Debug*>(
               &_Debug_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Debug* other);
  friend void swap(Debug& a, Debug& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Debug* New() const final {
    return CreateMaybeMessage<Debug>(NULL);
  }

  Debug* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Debug>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Debug& from);
  void MergeFrom(const Debug& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Debug* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .apollo.control.SimpleLongitudinalDebug simple_lon_debug = 1;
  bool has_simple_lon_debug() const;
  void clear_simple_lon_debug();
  static const int kSimpleLonDebugFieldNumber = 1;
  private:
  const ::apollo::control::SimpleLongitudinalDebug& _internal_simple_lon_debug() const;
  public:
  const ::apollo::control::SimpleLongitudinalDebug& simple_lon_debug() const;
  ::apollo::control::SimpleLongitudinalDebug* release_simple_lon_debug();
  ::apollo::control::SimpleLongitudinalDebug* mutable_simple_lon_debug();
  void set_allocated_simple_lon_debug(::apollo::control::SimpleLongitudinalDebug* simple_lon_debug);

  // .apollo.control.SimpleLateralDebug simple_lat_debug = 2;
  bool has_simple_lat_debug() const;
  void clear_simple_lat_debug();
  static const int kSimpleLatDebugFieldNumber = 2;
  private:
  const ::apollo::control::SimpleLateralDebug& _internal_simple_lat_debug() const;
  public:
  const ::apollo::control::SimpleLateralDebug& simple_lat_debug() const;
  ::apollo::control::SimpleLateralDebug* release_simple_lat_debug();
  ::apollo::control::SimpleLateralDebug* mutable_simple_lat_debug();
  void set_allocated_simple_lat_debug(::apollo::control::SimpleLateralDebug* simple_lat_debug);

  // .apollo.control.InputDebug input_debug = 3;
  bool has_input_debug() const;
  void clear_input_debug();
  static const int kInputDebugFieldNumber = 3;
  private:
  const ::apollo::control::InputDebug& _internal_input_debug() const;
  public:
  const ::apollo::control::InputDebug& input_debug() const;
  ::apollo::control::InputDebug* release_input_debug();
  ::apollo::control::InputDebug* mutable_input_debug();
  void set_allocated_input_debug(::apollo::control::InputDebug* input_debug);

  // @@protoc_insertion_point(class_scope:apollo.control.Debug)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::apollo::control::SimpleLongitudinalDebug* simple_lon_debug_;
  ::apollo::control::SimpleLateralDebug* simple_lat_debug_;
  ::apollo::control::InputDebug* input_debug_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LatencyStats

// double total_time_ms = 1;
inline void LatencyStats::clear_total_time_ms() {
  total_time_ms_ = 0;
}
inline double LatencyStats::total_time_ms() const {
  // @@protoc_insertion_point(field_get:apollo.control.LatencyStats.total_time_ms)
  return total_time_ms_;
}
inline void LatencyStats::set_total_time_ms(double value) {
  
  total_time_ms_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.LatencyStats.total_time_ms)
}

// repeated double controller_time_ms = 2;
inline int LatencyStats::controller_time_ms_size() const {
  return controller_time_ms_.size();
}
inline void LatencyStats::clear_controller_time_ms() {
  controller_time_ms_.Clear();
}
inline double LatencyStats::controller_time_ms(int index) const {
  // @@protoc_insertion_point(field_get:apollo.control.LatencyStats.controller_time_ms)
  return controller_time_ms_.Get(index);
}
inline void LatencyStats::set_controller_time_ms(int index, double value) {
  controller_time_ms_.Set(index, value);
  // @@protoc_insertion_point(field_set:apollo.control.LatencyStats.controller_time_ms)
}
inline void LatencyStats::add_controller_time_ms(double value) {
  controller_time_ms_.Add(value);
  // @@protoc_insertion_point(field_add:apollo.control.LatencyStats.controller_time_ms)
}
inline const ::google::protobuf::RepeatedField< double >&
LatencyStats::controller_time_ms() const {
  // @@protoc_insertion_point(field_list:apollo.control.LatencyStats.controller_time_ms)
  return controller_time_ms_;
}
inline ::google::protobuf::RepeatedField< double >*
LatencyStats::mutable_controller_time_ms() {
  // @@protoc_insertion_point(field_mutable_list:apollo.control.LatencyStats.controller_time_ms)
  return &controller_time_ms_;
}

// -------------------------------------------------------------------

// ControlCommand

// .apollo.common.Header header = 1;
inline bool ControlCommand::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::apollo::common::Header& ControlCommand::_internal_header() const {
  return *header_;
}
inline const ::apollo::common::Header& ControlCommand::header() const {
  const ::apollo::common::Header* p = header_;
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* ControlCommand::release_header() {
  // @@protoc_insertion_point(field_release:apollo.control.ControlCommand.header)
  
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::apollo::common::Header* ControlCommand::mutable_header() {
  
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.ControlCommand.header)
  return header_;
}
inline void ControlCommand::set_allocated_header(::apollo::common::Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.ControlCommand.header)
}

// double throttle = 3;
inline void ControlCommand::clear_throttle() {
  throttle_ = 0;
}
inline double ControlCommand::throttle() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.throttle)
  return throttle_;
}
inline void ControlCommand::set_throttle(double value) {
  
  throttle_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.throttle)
}

// double brake = 4;
inline void ControlCommand::clear_brake() {
  brake_ = 0;
}
inline double ControlCommand::brake() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.brake)
  return brake_;
}
inline void ControlCommand::set_brake(double value) {
  
  brake_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.brake)
}

// double steering_rate = 6;
inline void ControlCommand::clear_steering_rate() {
  steering_rate_ = 0;
}
inline double ControlCommand::steering_rate() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.steering_rate)
  return steering_rate_;
}
inline void ControlCommand::set_steering_rate(double value) {
  
  steering_rate_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.steering_rate)
}

// double steering_target = 7;
inline void ControlCommand::clear_steering_target() {
  steering_target_ = 0;
}
inline double ControlCommand::steering_target() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.steering_target)
  return steering_target_;
}
inline void ControlCommand::set_steering_target(double value) {
  
  steering_target_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.steering_target)
}

// bool parking_brake = 8;
inline void ControlCommand::clear_parking_brake() {
  parking_brake_ = false;
}
inline bool ControlCommand::parking_brake() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.parking_brake)
  return parking_brake_;
}
inline void ControlCommand::set_parking_brake(bool value) {
  
  parking_brake_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.parking_brake)
}

// double speed = 9;
inline void ControlCommand::clear_speed() {
  speed_ = 0;
}
inline double ControlCommand::speed() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.speed)
  return speed_;
}
inline void ControlCommand::set_speed(double value) {
  
  speed_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.speed)
}

// double acceleration = 10;
inline void ControlCommand::clear_acceleration() {
  acceleration_ = 0;
}
inline double ControlCommand::acceleration() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.acceleration)
  return acceleration_;
}
inline void ControlCommand::set_acceleration(double value) {
  
  acceleration_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.acceleration)
}

// bool reset_model = 16;
inline void ControlCommand::clear_reset_model() {
  reset_model_ = false;
}
inline bool ControlCommand::reset_model() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.reset_model)
  return reset_model_;
}
inline void ControlCommand::set_reset_model(bool value) {
  
  reset_model_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.reset_model)
}

// bool engine_on_off = 17;
inline void ControlCommand::clear_engine_on_off() {
  engine_on_off_ = false;
}
inline bool ControlCommand::engine_on_off() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.engine_on_off)
  return engine_on_off_;
}
inline void ControlCommand::set_engine_on_off(bool value) {
  
  engine_on_off_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.engine_on_off)
}

// double trajectory_fraction = 18;
inline void ControlCommand::clear_trajectory_fraction() {
  trajectory_fraction_ = 0;
}
inline double ControlCommand::trajectory_fraction() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.trajectory_fraction)
  return trajectory_fraction_;
}
inline void ControlCommand::set_trajectory_fraction(double value) {
  
  trajectory_fraction_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.trajectory_fraction)
}

// .apollo.canbus.Chassis.DrivingMode driving_mode = 19;
inline void ControlCommand::clear_driving_mode() {
  driving_mode_ = 0;
}
inline ::apollo::canbus::Chassis_DrivingMode ControlCommand::driving_mode() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.driving_mode)
  return static_cast< ::apollo::canbus::Chassis_DrivingMode >(driving_mode_);
}
inline void ControlCommand::set_driving_mode(::apollo::canbus::Chassis_DrivingMode value) {
  
  driving_mode_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.driving_mode)
}

// .apollo.canbus.Chassis.GearPosition gear_location = 20;
inline void ControlCommand::clear_gear_location() {
  gear_location_ = 0;
}
inline ::apollo::canbus::Chassis_GearPosition ControlCommand::gear_location() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.gear_location)
  return static_cast< ::apollo::canbus::Chassis_GearPosition >(gear_location_);
}
inline void ControlCommand::set_gear_location(::apollo::canbus::Chassis_GearPosition value) {
  
  gear_location_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.gear_location)
}

// .apollo.control.Debug debug = 22;
inline bool ControlCommand::has_debug() const {
  return this != internal_default_instance() && debug_ != NULL;
}
inline void ControlCommand::clear_debug() {
  if (GetArenaNoVirtual() == NULL && debug_ != NULL) {
    delete debug_;
  }
  debug_ = NULL;
}
inline const ::apollo::control::Debug& ControlCommand::_internal_debug() const {
  return *debug_;
}
inline const ::apollo::control::Debug& ControlCommand::debug() const {
  const ::apollo::control::Debug* p = debug_;
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.debug)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::control::Debug*>(
      &::apollo::control::_Debug_default_instance_);
}
inline ::apollo::control::Debug* ControlCommand::release_debug() {
  // @@protoc_insertion_point(field_release:apollo.control.ControlCommand.debug)
  
  ::apollo::control::Debug* temp = debug_;
  debug_ = NULL;
  return temp;
}
inline ::apollo::control::Debug* ControlCommand::mutable_debug() {
  
  if (debug_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::control::Debug>(GetArenaNoVirtual());
    debug_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.ControlCommand.debug)
  return debug_;
}
inline void ControlCommand::set_allocated_debug(::apollo::control::Debug* debug) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete debug_;
  }
  if (debug) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      debug = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, debug, submessage_arena);
    }
    
  } else {
    
  }
  debug_ = debug;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.ControlCommand.debug)
}

// .apollo.canbus.Signal signal = 23;
inline bool ControlCommand::has_signal() const {
  return this != internal_default_instance() && signal_ != NULL;
}
inline const ::apollo::canbus::Signal& ControlCommand::_internal_signal() const {
  return *signal_;
}
inline const ::apollo::canbus::Signal& ControlCommand::signal() const {
  const ::apollo::canbus::Signal* p = signal_;
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.signal)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::canbus::Signal*>(
      &::apollo::canbus::_Signal_default_instance_);
}
inline ::apollo::canbus::Signal* ControlCommand::release_signal() {
  // @@protoc_insertion_point(field_release:apollo.control.ControlCommand.signal)
  
  ::apollo::canbus::Signal* temp = signal_;
  signal_ = NULL;
  return temp;
}
inline ::apollo::canbus::Signal* ControlCommand::mutable_signal() {
  
  if (signal_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::canbus::Signal>(GetArenaNoVirtual());
    signal_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.ControlCommand.signal)
  return signal_;
}
inline void ControlCommand::set_allocated_signal(::apollo::canbus::Signal* signal) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(signal_);
  }
  if (signal) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      signal = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, signal, submessage_arena);
    }
    
  } else {
    
  }
  signal_ = signal;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.ControlCommand.signal)
}

// .apollo.control.LatencyStats latency_stats = 24;
inline bool ControlCommand::has_latency_stats() const {
  return this != internal_default_instance() && latency_stats_ != NULL;
}
inline void ControlCommand::clear_latency_stats() {
  if (GetArenaNoVirtual() == NULL && latency_stats_ != NULL) {
    delete latency_stats_;
  }
  latency_stats_ = NULL;
}
inline const ::apollo::control::LatencyStats& ControlCommand::_internal_latency_stats() const {
  return *latency_stats_;
}
inline const ::apollo::control::LatencyStats& ControlCommand::latency_stats() const {
  const ::apollo::control::LatencyStats* p = latency_stats_;
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.latency_stats)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::control::LatencyStats*>(
      &::apollo::control::_LatencyStats_default_instance_);
}
inline ::apollo::control::LatencyStats* ControlCommand::release_latency_stats() {
  // @@protoc_insertion_point(field_release:apollo.control.ControlCommand.latency_stats)
  
  ::apollo::control::LatencyStats* temp = latency_stats_;
  latency_stats_ = NULL;
  return temp;
}
inline ::apollo::control::LatencyStats* ControlCommand::mutable_latency_stats() {
  
  if (latency_stats_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::control::LatencyStats>(GetArenaNoVirtual());
    latency_stats_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.ControlCommand.latency_stats)
  return latency_stats_;
}
inline void ControlCommand::set_allocated_latency_stats(::apollo::control::LatencyStats* latency_stats) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete latency_stats_;
  }
  if (latency_stats) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      latency_stats = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, latency_stats, submessage_arena);
    }
    
  } else {
    
  }
  latency_stats_ = latency_stats;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.ControlCommand.latency_stats)
}

// .apollo.control.PadMessage pad_msg = 25;
inline bool ControlCommand::has_pad_msg() const {
  return this != internal_default_instance() && pad_msg_ != NULL;
}
inline const ::apollo::control::PadMessage& ControlCommand::_internal_pad_msg() const {
  return *pad_msg_;
}
inline const ::apollo::control::PadMessage& ControlCommand::pad_msg() const {
  const ::apollo::control::PadMessage* p = pad_msg_;
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.pad_msg)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::control::PadMessage*>(
      &::apollo::control::_PadMessage_default_instance_);
}
inline ::apollo::control::PadMessage* ControlCommand::release_pad_msg() {
  // @@protoc_insertion_point(field_release:apollo.control.ControlCommand.pad_msg)
  
  ::apollo::control::PadMessage* temp = pad_msg_;
  pad_msg_ = NULL;
  return temp;
}
inline ::apollo::control::PadMessage* ControlCommand::mutable_pad_msg() {
  
  if (pad_msg_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::control::PadMessage>(GetArenaNoVirtual());
    pad_msg_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.ControlCommand.pad_msg)
  return pad_msg_;
}
inline void ControlCommand::set_allocated_pad_msg(::apollo::control::PadMessage* pad_msg) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(pad_msg_);
  }
  if (pad_msg) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pad_msg = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pad_msg, submessage_arena);
    }
    
  } else {
    
  }
  pad_msg_ = pad_msg;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.ControlCommand.pad_msg)
}

// bool left_turn = 13;
inline void ControlCommand::clear_left_turn() {
  left_turn_ = false;
}
inline bool ControlCommand::left_turn() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.left_turn)
  return left_turn_;
}
inline void ControlCommand::set_left_turn(bool value) {
  
  left_turn_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.left_turn)
}

// bool right_turn = 14;
inline void ControlCommand::clear_right_turn() {
  right_turn_ = false;
}
inline bool ControlCommand::right_turn() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.right_turn)
  return right_turn_;
}
inline void ControlCommand::set_right_turn(bool value) {
  
  right_turn_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.right_turn)
}

// bool high_beam = 11;
inline void ControlCommand::clear_high_beam() {
  high_beam_ = false;
}
inline bool ControlCommand::high_beam() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.high_beam)
  return high_beam_;
}
inline void ControlCommand::set_high_beam(bool value) {
  
  high_beam_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.high_beam)
}

// bool low_beam = 12;
inline void ControlCommand::clear_low_beam() {
  low_beam_ = false;
}
inline bool ControlCommand::low_beam() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.low_beam)
  return low_beam_;
}
inline void ControlCommand::set_low_beam(bool value) {
  
  low_beam_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.low_beam)
}

// bool horn = 15;
inline void ControlCommand::clear_horn() {
  horn_ = false;
}
inline bool ControlCommand::horn() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.horn)
  return horn_;
}
inline void ControlCommand::set_horn(bool value) {
  
  horn_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.horn)
}

// .apollo.control.TurnSignal turnsignal = 21;
inline void ControlCommand::clear_turnsignal() {
  turnsignal_ = 0;
}
inline ::apollo::control::TurnSignal ControlCommand::turnsignal() const {
  // @@protoc_insertion_point(field_get:apollo.control.ControlCommand.turnsignal)
  return static_cast< ::apollo::control::TurnSignal >(turnsignal_);
}
inline void ControlCommand::set_turnsignal(::apollo::control::TurnSignal value) {
  
  turnsignal_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.ControlCommand.turnsignal)
}

// -------------------------------------------------------------------

// SimpleLongitudinalDebug

// double station_reference = 1;
inline void SimpleLongitudinalDebug::clear_station_reference() {
  station_reference_ = 0;
}
inline double SimpleLongitudinalDebug::station_reference() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.station_reference)
  return station_reference_;
}
inline void SimpleLongitudinalDebug::set_station_reference(double value) {
  
  station_reference_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.station_reference)
}

// double station_error = 2;
inline void SimpleLongitudinalDebug::clear_station_error() {
  station_error_ = 0;
}
inline double SimpleLongitudinalDebug::station_error() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.station_error)
  return station_error_;
}
inline void SimpleLongitudinalDebug::set_station_error(double value) {
  
  station_error_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.station_error)
}

// double station_error_limited = 3;
inline void SimpleLongitudinalDebug::clear_station_error_limited() {
  station_error_limited_ = 0;
}
inline double SimpleLongitudinalDebug::station_error_limited() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.station_error_limited)
  return station_error_limited_;
}
inline void SimpleLongitudinalDebug::set_station_error_limited(double value) {
  
  station_error_limited_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.station_error_limited)
}

// double preview_station_error = 4;
inline void SimpleLongitudinalDebug::clear_preview_station_error() {
  preview_station_error_ = 0;
}
inline double SimpleLongitudinalDebug::preview_station_error() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.preview_station_error)
  return preview_station_error_;
}
inline void SimpleLongitudinalDebug::set_preview_station_error(double value) {
  
  preview_station_error_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.preview_station_error)
}

// double speed_reference = 5;
inline void SimpleLongitudinalDebug::clear_speed_reference() {
  speed_reference_ = 0;
}
inline double SimpleLongitudinalDebug::speed_reference() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.speed_reference)
  return speed_reference_;
}
inline void SimpleLongitudinalDebug::set_speed_reference(double value) {
  
  speed_reference_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.speed_reference)
}

// double speed_error = 6;
inline void SimpleLongitudinalDebug::clear_speed_error() {
  speed_error_ = 0;
}
inline double SimpleLongitudinalDebug::speed_error() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.speed_error)
  return speed_error_;
}
inline void SimpleLongitudinalDebug::set_speed_error(double value) {
  
  speed_error_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.speed_error)
}

// double speed_controller_input_limited = 7;
inline void SimpleLongitudinalDebug::clear_speed_controller_input_limited() {
  speed_controller_input_limited_ = 0;
}
inline double SimpleLongitudinalDebug::speed_controller_input_limited() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.speed_controller_input_limited)
  return speed_controller_input_limited_;
}
inline void SimpleLongitudinalDebug::set_speed_controller_input_limited(double value) {
  
  speed_controller_input_limited_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.speed_controller_input_limited)
}

// double preview_speed_reference = 8;
inline void SimpleLongitudinalDebug::clear_preview_speed_reference() {
  preview_speed_reference_ = 0;
}
inline double SimpleLongitudinalDebug::preview_speed_reference() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.preview_speed_reference)
  return preview_speed_reference_;
}
inline void SimpleLongitudinalDebug::set_preview_speed_reference(double value) {
  
  preview_speed_reference_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.preview_speed_reference)
}

// double preview_speed_error = 9;
inline void SimpleLongitudinalDebug::clear_preview_speed_error() {
  preview_speed_error_ = 0;
}
inline double SimpleLongitudinalDebug::preview_speed_error() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.preview_speed_error)
  return preview_speed_error_;
}
inline void SimpleLongitudinalDebug::set_preview_speed_error(double value) {
  
  preview_speed_error_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.preview_speed_error)
}

// double preview_acceleration_reference = 10;
inline void SimpleLongitudinalDebug::clear_preview_acceleration_reference() {
  preview_acceleration_reference_ = 0;
}
inline double SimpleLongitudinalDebug::preview_acceleration_reference() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.preview_acceleration_reference)
  return preview_acceleration_reference_;
}
inline void SimpleLongitudinalDebug::set_preview_acceleration_reference(double value) {
  
  preview_acceleration_reference_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.preview_acceleration_reference)
}

// double acceleration_cmd_closeloop = 11;
inline void SimpleLongitudinalDebug::clear_acceleration_cmd_closeloop() {
  acceleration_cmd_closeloop_ = 0;
}
inline double SimpleLongitudinalDebug::acceleration_cmd_closeloop() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.acceleration_cmd_closeloop)
  return acceleration_cmd_closeloop_;
}
inline void SimpleLongitudinalDebug::set_acceleration_cmd_closeloop(double value) {
  
  acceleration_cmd_closeloop_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.acceleration_cmd_closeloop)
}

// double acceleration_cmd = 12;
inline void SimpleLongitudinalDebug::clear_acceleration_cmd() {
  acceleration_cmd_ = 0;
}
inline double SimpleLongitudinalDebug::acceleration_cmd() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.acceleration_cmd)
  return acceleration_cmd_;
}
inline void SimpleLongitudinalDebug::set_acceleration_cmd(double value) {
  
  acceleration_cmd_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.acceleration_cmd)
}

// double acceleration_lookup = 13;
inline void SimpleLongitudinalDebug::clear_acceleration_lookup() {
  acceleration_lookup_ = 0;
}
inline double SimpleLongitudinalDebug::acceleration_lookup() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.acceleration_lookup)
  return acceleration_lookup_;
}
inline void SimpleLongitudinalDebug::set_acceleration_lookup(double value) {
  
  acceleration_lookup_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.acceleration_lookup)
}

// double speed_lookup = 14;
inline void SimpleLongitudinalDebug::clear_speed_lookup() {
  speed_lookup_ = 0;
}
inline double SimpleLongitudinalDebug::speed_lookup() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.speed_lookup)
  return speed_lookup_;
}
inline void SimpleLongitudinalDebug::set_speed_lookup(double value) {
  
  speed_lookup_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.speed_lookup)
}

// double calibration_value = 15;
inline void SimpleLongitudinalDebug::clear_calibration_value() {
  calibration_value_ = 0;
}
inline double SimpleLongitudinalDebug::calibration_value() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.calibration_value)
  return calibration_value_;
}
inline void SimpleLongitudinalDebug::set_calibration_value(double value) {
  
  calibration_value_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.calibration_value)
}

// double throttle_cmd = 16;
inline void SimpleLongitudinalDebug::clear_throttle_cmd() {
  throttle_cmd_ = 0;
}
inline double SimpleLongitudinalDebug::throttle_cmd() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.throttle_cmd)
  return throttle_cmd_;
}
inline void SimpleLongitudinalDebug::set_throttle_cmd(double value) {
  
  throttle_cmd_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.throttle_cmd)
}

// double brake_cmd = 17;
inline void SimpleLongitudinalDebug::clear_brake_cmd() {
  brake_cmd_ = 0;
}
inline double SimpleLongitudinalDebug::brake_cmd() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.brake_cmd)
  return brake_cmd_;
}
inline void SimpleLongitudinalDebug::set_brake_cmd(double value) {
  
  brake_cmd_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.brake_cmd)
}

// bool is_full_stop = 18;
inline void SimpleLongitudinalDebug::clear_is_full_stop() {
  is_full_stop_ = false;
}
inline bool SimpleLongitudinalDebug::is_full_stop() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLongitudinalDebug.is_full_stop)
  return is_full_stop_;
}
inline void SimpleLongitudinalDebug::set_is_full_stop(bool value) {
  
  is_full_stop_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLongitudinalDebug.is_full_stop)
}

// -------------------------------------------------------------------

// SimpleLateralDebug

// double lateral_error = 1;
inline void SimpleLateralDebug::clear_lateral_error() {
  lateral_error_ = 0;
}
inline double SimpleLateralDebug::lateral_error() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.lateral_error)
  return lateral_error_;
}
inline void SimpleLateralDebug::set_lateral_error(double value) {
  
  lateral_error_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.lateral_error)
}

// double ref_heading = 2;
inline void SimpleLateralDebug::clear_ref_heading() {
  ref_heading_ = 0;
}
inline double SimpleLateralDebug::ref_heading() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.ref_heading)
  return ref_heading_;
}
inline void SimpleLateralDebug::set_ref_heading(double value) {
  
  ref_heading_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.ref_heading)
}

// double heading = 3;
inline void SimpleLateralDebug::clear_heading() {
  heading_ = 0;
}
inline double SimpleLateralDebug::heading() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.heading)
  return heading_;
}
inline void SimpleLateralDebug::set_heading(double value) {
  
  heading_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.heading)
}

// double heading_error = 4;
inline void SimpleLateralDebug::clear_heading_error() {
  heading_error_ = 0;
}
inline double SimpleLateralDebug::heading_error() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.heading_error)
  return heading_error_;
}
inline void SimpleLateralDebug::set_heading_error(double value) {
  
  heading_error_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.heading_error)
}

// double heading_error_rate = 5;
inline void SimpleLateralDebug::clear_heading_error_rate() {
  heading_error_rate_ = 0;
}
inline double SimpleLateralDebug::heading_error_rate() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.heading_error_rate)
  return heading_error_rate_;
}
inline void SimpleLateralDebug::set_heading_error_rate(double value) {
  
  heading_error_rate_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.heading_error_rate)
}

// double lateral_error_rate = 6;
inline void SimpleLateralDebug::clear_lateral_error_rate() {
  lateral_error_rate_ = 0;
}
inline double SimpleLateralDebug::lateral_error_rate() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.lateral_error_rate)
  return lateral_error_rate_;
}
inline void SimpleLateralDebug::set_lateral_error_rate(double value) {
  
  lateral_error_rate_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.lateral_error_rate)
}

// double curvature = 7;
inline void SimpleLateralDebug::clear_curvature() {
  curvature_ = 0;
}
inline double SimpleLateralDebug::curvature() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.curvature)
  return curvature_;
}
inline void SimpleLateralDebug::set_curvature(double value) {
  
  curvature_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.curvature)
}

// double steer_angle = 8;
inline void SimpleLateralDebug::clear_steer_angle() {
  steer_angle_ = 0;
}
inline double SimpleLateralDebug::steer_angle() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steer_angle)
  return steer_angle_;
}
inline void SimpleLateralDebug::set_steer_angle(double value) {
  
  steer_angle_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steer_angle)
}

// double steer_angle_feedforward = 9;
inline void SimpleLateralDebug::clear_steer_angle_feedforward() {
  steer_angle_feedforward_ = 0;
}
inline double SimpleLateralDebug::steer_angle_feedforward() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steer_angle_feedforward)
  return steer_angle_feedforward_;
}
inline void SimpleLateralDebug::set_steer_angle_feedforward(double value) {
  
  steer_angle_feedforward_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steer_angle_feedforward)
}

// double steer_angle_lateral_contribution = 10;
inline void SimpleLateralDebug::clear_steer_angle_lateral_contribution() {
  steer_angle_lateral_contribution_ = 0;
}
inline double SimpleLateralDebug::steer_angle_lateral_contribution() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steer_angle_lateral_contribution)
  return steer_angle_lateral_contribution_;
}
inline void SimpleLateralDebug::set_steer_angle_lateral_contribution(double value) {
  
  steer_angle_lateral_contribution_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steer_angle_lateral_contribution)
}

// double steer_angle_lateral_rate_contribution = 11;
inline void SimpleLateralDebug::clear_steer_angle_lateral_rate_contribution() {
  steer_angle_lateral_rate_contribution_ = 0;
}
inline double SimpleLateralDebug::steer_angle_lateral_rate_contribution() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steer_angle_lateral_rate_contribution)
  return steer_angle_lateral_rate_contribution_;
}
inline void SimpleLateralDebug::set_steer_angle_lateral_rate_contribution(double value) {
  
  steer_angle_lateral_rate_contribution_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steer_angle_lateral_rate_contribution)
}

// double steer_angle_heading_contribution = 12;
inline void SimpleLateralDebug::clear_steer_angle_heading_contribution() {
  steer_angle_heading_contribution_ = 0;
}
inline double SimpleLateralDebug::steer_angle_heading_contribution() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steer_angle_heading_contribution)
  return steer_angle_heading_contribution_;
}
inline void SimpleLateralDebug::set_steer_angle_heading_contribution(double value) {
  
  steer_angle_heading_contribution_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steer_angle_heading_contribution)
}

// double steer_angle_heading_rate_contribution = 13;
inline void SimpleLateralDebug::clear_steer_angle_heading_rate_contribution() {
  steer_angle_heading_rate_contribution_ = 0;
}
inline double SimpleLateralDebug::steer_angle_heading_rate_contribution() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steer_angle_heading_rate_contribution)
  return steer_angle_heading_rate_contribution_;
}
inline void SimpleLateralDebug::set_steer_angle_heading_rate_contribution(double value) {
  
  steer_angle_heading_rate_contribution_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steer_angle_heading_rate_contribution)
}

// double steer_angle_feedback = 14;
inline void SimpleLateralDebug::clear_steer_angle_feedback() {
  steer_angle_feedback_ = 0;
}
inline double SimpleLateralDebug::steer_angle_feedback() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steer_angle_feedback)
  return steer_angle_feedback_;
}
inline void SimpleLateralDebug::set_steer_angle_feedback(double value) {
  
  steer_angle_feedback_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steer_angle_feedback)
}

// double steering_position = 15;
inline void SimpleLateralDebug::clear_steering_position() {
  steering_position_ = 0;
}
inline double SimpleLateralDebug::steering_position() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.steering_position)
  return steering_position_;
}
inline void SimpleLateralDebug::set_steering_position(double value) {
  
  steering_position_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.steering_position)
}

// double ref_speed = 16;
inline void SimpleLateralDebug::clear_ref_speed() {
  ref_speed_ = 0;
}
inline double SimpleLateralDebug::ref_speed() const {
  // @@protoc_insertion_point(field_get:apollo.control.SimpleLateralDebug.ref_speed)
  return ref_speed_;
}
inline void SimpleLateralDebug::set_ref_speed(double value) {
  
  ref_speed_ = value;
  // @@protoc_insertion_point(field_set:apollo.control.SimpleLateralDebug.ref_speed)
}

// -------------------------------------------------------------------

// InputDebug

// .apollo.common.Header localization_header = 1;
inline bool InputDebug::has_localization_header() const {
  return this != internal_default_instance() && localization_header_ != NULL;
}
inline const ::apollo::common::Header& InputDebug::_internal_localization_header() const {
  return *localization_header_;
}
inline const ::apollo::common::Header& InputDebug::localization_header() const {
  const ::apollo::common::Header* p = localization_header_;
  // @@protoc_insertion_point(field_get:apollo.control.InputDebug.localization_header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* InputDebug::release_localization_header() {
  // @@protoc_insertion_point(field_release:apollo.control.InputDebug.localization_header)
  
  ::apollo::common::Header* temp = localization_header_;
  localization_header_ = NULL;
  return temp;
}
inline ::apollo::common::Header* InputDebug::mutable_localization_header() {
  
  if (localization_header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArenaNoVirtual());
    localization_header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.InputDebug.localization_header)
  return localization_header_;
}
inline void InputDebug::set_allocated_localization_header(::apollo::common::Header* localization_header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(localization_header_);
  }
  if (localization_header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      localization_header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, localization_header, submessage_arena);
    }
    
  } else {
    
  }
  localization_header_ = localization_header;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.InputDebug.localization_header)
}

// .apollo.common.Header canbus_header = 2;
inline bool InputDebug::has_canbus_header() const {
  return this != internal_default_instance() && canbus_header_ != NULL;
}
inline const ::apollo::common::Header& InputDebug::_internal_canbus_header() const {
  return *canbus_header_;
}
inline const ::apollo::common::Header& InputDebug::canbus_header() const {
  const ::apollo::common::Header* p = canbus_header_;
  // @@protoc_insertion_point(field_get:apollo.control.InputDebug.canbus_header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* InputDebug::release_canbus_header() {
  // @@protoc_insertion_point(field_release:apollo.control.InputDebug.canbus_header)
  
  ::apollo::common::Header* temp = canbus_header_;
  canbus_header_ = NULL;
  return temp;
}
inline ::apollo::common::Header* InputDebug::mutable_canbus_header() {
  
  if (canbus_header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArenaNoVirtual());
    canbus_header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.InputDebug.canbus_header)
  return canbus_header_;
}
inline void InputDebug::set_allocated_canbus_header(::apollo::common::Header* canbus_header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(canbus_header_);
  }
  if (canbus_header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      canbus_header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, canbus_header, submessage_arena);
    }
    
  } else {
    
  }
  canbus_header_ = canbus_header;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.InputDebug.canbus_header)
}

// .apollo.common.Header trajectory_header = 3;
inline bool InputDebug::has_trajectory_header() const {
  return this != internal_default_instance() && trajectory_header_ != NULL;
}
inline const ::apollo::common::Header& InputDebug::_internal_trajectory_header() const {
  return *trajectory_header_;
}
inline const ::apollo::common::Header& InputDebug::trajectory_header() const {
  const ::apollo::common::Header* p = trajectory_header_;
  // @@protoc_insertion_point(field_get:apollo.control.InputDebug.trajectory_header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::common::Header*>(
      &::apollo::common::_Header_default_instance_);
}
inline ::apollo::common::Header* InputDebug::release_trajectory_header() {
  // @@protoc_insertion_point(field_release:apollo.control.InputDebug.trajectory_header)
  
  ::apollo::common::Header* temp = trajectory_header_;
  trajectory_header_ = NULL;
  return temp;
}
inline ::apollo::common::Header* InputDebug::mutable_trajectory_header() {
  
  if (trajectory_header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::common::Header>(GetArenaNoVirtual());
    trajectory_header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.InputDebug.trajectory_header)
  return trajectory_header_;
}
inline void InputDebug::set_allocated_trajectory_header(::apollo::common::Header* trajectory_header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(trajectory_header_);
  }
  if (trajectory_header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      trajectory_header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, trajectory_header, submessage_arena);
    }
    
  } else {
    
  }
  trajectory_header_ = trajectory_header;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.InputDebug.trajectory_header)
}

// -------------------------------------------------------------------

// Debug

// .apollo.control.SimpleLongitudinalDebug simple_lon_debug = 1;
inline bool Debug::has_simple_lon_debug() const {
  return this != internal_default_instance() && simple_lon_debug_ != NULL;
}
inline void Debug::clear_simple_lon_debug() {
  if (GetArenaNoVirtual() == NULL && simple_lon_debug_ != NULL) {
    delete simple_lon_debug_;
  }
  simple_lon_debug_ = NULL;
}
inline const ::apollo::control::SimpleLongitudinalDebug& Debug::_internal_simple_lon_debug() const {
  return *simple_lon_debug_;
}
inline const ::apollo::control::SimpleLongitudinalDebug& Debug::simple_lon_debug() const {
  const ::apollo::control::SimpleLongitudinalDebug* p = simple_lon_debug_;
  // @@protoc_insertion_point(field_get:apollo.control.Debug.simple_lon_debug)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::control::SimpleLongitudinalDebug*>(
      &::apollo::control::_SimpleLongitudinalDebug_default_instance_);
}
inline ::apollo::control::SimpleLongitudinalDebug* Debug::release_simple_lon_debug() {
  // @@protoc_insertion_point(field_release:apollo.control.Debug.simple_lon_debug)
  
  ::apollo::control::SimpleLongitudinalDebug* temp = simple_lon_debug_;
  simple_lon_debug_ = NULL;
  return temp;
}
inline ::apollo::control::SimpleLongitudinalDebug* Debug::mutable_simple_lon_debug() {
  
  if (simple_lon_debug_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::control::SimpleLongitudinalDebug>(GetArenaNoVirtual());
    simple_lon_debug_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.Debug.simple_lon_debug)
  return simple_lon_debug_;
}
inline void Debug::set_allocated_simple_lon_debug(::apollo::control::SimpleLongitudinalDebug* simple_lon_debug) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete simple_lon_debug_;
  }
  if (simple_lon_debug) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      simple_lon_debug = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, simple_lon_debug, submessage_arena);
    }
    
  } else {
    
  }
  simple_lon_debug_ = simple_lon_debug;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.Debug.simple_lon_debug)
}

// .apollo.control.SimpleLateralDebug simple_lat_debug = 2;
inline bool Debug::has_simple_lat_debug() const {
  return this != internal_default_instance() && simple_lat_debug_ != NULL;
}
inline void Debug::clear_simple_lat_debug() {
  if (GetArenaNoVirtual() == NULL && simple_lat_debug_ != NULL) {
    delete simple_lat_debug_;
  }
  simple_lat_debug_ = NULL;
}
inline const ::apollo::control::SimpleLateralDebug& Debug::_internal_simple_lat_debug() const {
  return *simple_lat_debug_;
}
inline const ::apollo::control::SimpleLateralDebug& Debug::simple_lat_debug() const {
  const ::apollo::control::SimpleLateralDebug* p = simple_lat_debug_;
  // @@protoc_insertion_point(field_get:apollo.control.Debug.simple_lat_debug)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::control::SimpleLateralDebug*>(
      &::apollo::control::_SimpleLateralDebug_default_instance_);
}
inline ::apollo::control::SimpleLateralDebug* Debug::release_simple_lat_debug() {
  // @@protoc_insertion_point(field_release:apollo.control.Debug.simple_lat_debug)
  
  ::apollo::control::SimpleLateralDebug* temp = simple_lat_debug_;
  simple_lat_debug_ = NULL;
  return temp;
}
inline ::apollo::control::SimpleLateralDebug* Debug::mutable_simple_lat_debug() {
  
  if (simple_lat_debug_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::control::SimpleLateralDebug>(GetArenaNoVirtual());
    simple_lat_debug_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.Debug.simple_lat_debug)
  return simple_lat_debug_;
}
inline void Debug::set_allocated_simple_lat_debug(::apollo::control::SimpleLateralDebug* simple_lat_debug) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete simple_lat_debug_;
  }
  if (simple_lat_debug) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      simple_lat_debug = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, simple_lat_debug, submessage_arena);
    }
    
  } else {
    
  }
  simple_lat_debug_ = simple_lat_debug;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.Debug.simple_lat_debug)
}

// .apollo.control.InputDebug input_debug = 3;
inline bool Debug::has_input_debug() const {
  return this != internal_default_instance() && input_debug_ != NULL;
}
inline void Debug::clear_input_debug() {
  if (GetArenaNoVirtual() == NULL && input_debug_ != NULL) {
    delete input_debug_;
  }
  input_debug_ = NULL;
}
inline const ::apollo::control::InputDebug& Debug::_internal_input_debug() const {
  return *input_debug_;
}
inline const ::apollo::control::InputDebug& Debug::input_debug() const {
  const ::apollo::control::InputDebug* p = input_debug_;
  // @@protoc_insertion_point(field_get:apollo.control.Debug.input_debug)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::control::InputDebug*>(
      &::apollo::control::_InputDebug_default_instance_);
}
inline ::apollo::control::InputDebug* Debug::release_input_debug() {
  // @@protoc_insertion_point(field_release:apollo.control.Debug.input_debug)
  
  ::apollo::control::InputDebug* temp = input_debug_;
  input_debug_ = NULL;
  return temp;
}
inline ::apollo::control::InputDebug* Debug::mutable_input_debug() {
  
  if (input_debug_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::control::InputDebug>(GetArenaNoVirtual());
    input_debug_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.control.Debug.input_debug)
  return input_debug_;
}
inline void Debug::set_allocated_input_debug(::apollo::control::InputDebug* input_debug) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete input_debug_;
  }
  if (input_debug) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      input_debug = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, input_debug, submessage_arena);
    }
    
  } else {
    
  }
  input_debug_ = input_debug;
  // @@protoc_insertion_point(field_set_allocated:apollo.control.Debug.input_debug)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace control
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::control::TurnSignal> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::control::TurnSignal>() {
  return ::apollo::control::TurnSignal_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_apollo_5fmsgs_2fproto_2fcontrol_2fcontrol_5fcmd_2eproto
